---
title: "Binomial Logistic Regression - 180 days"
author: "Jessica George and Shawna Tuli"
date: "7/6/2021"
output:
  html_document: default
  pdf_document: default
---

# Libraries
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
library(survival)
library(lubridate)
library(gtsummary)

source("../format_data.R")
```

# Data
```{r message=FALSE, warning=FALSE, include=FALSE}
original <- read_excel("../../data/time_to_treatment_data.xlsx") %>% 
  format_data(article_number = 3)

# grab RT/CRT patients only
data <- original %>% filter(rt == "Yes" | crt == "Yes")

uni_predictors <- c("enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")
```

# Functions
```{r include=FALSE}
overall_univariate_logistic_regresion <- function(resp, predictors) {
  formula <- as.formula(paste(resp, predictors, sep = " ~ "))
  overall.logist <- glm(formula, data = data, family = binomial)
  return(overall.logist)
}

overall_multivariate_logistic_regresion <- function(resp, predictors) {
  formula <- as.formula(paste(resp, paste(predictors, collapse = " + "), sep = " ~ "))
  overall.logist <- glm(formula, data = data, family = binomial)
  return(overall.logist)
}
```

# Univariate Models - 30 day delays
```{r echo=FALSE}
tbl_uvregression(data=data[c("path_treatment_30", "enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")],
                 method = glm, 
                 y = path_treatment_30,
                 method.args=list(family=binomial),
                 include = uni_predictors,
                 hide_n = 2,
                 exponentiate = TRUE)
```

# Univariate Models - 60 day delays
```{r echo=FALSE}
tbl_uvregression(data=data[c("path_treatment_60", "enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")],
                 method = glm, 
                 y = path_treatment_60,
                 method.args=list(family=binomial),
                 include = uni_predictors,
                 hide_n = 2,
                 exponentiate = TRUE)
```

# Univariate Models - 90 day delays
```{r echo=FALSE}
tbl_uvregression(data=data[c("path_treatment_90", "enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")],
                 method = glm, 
                 y = path_treatment_90,
                 method.args=list(family=binomial),
                 include = uni_predictors,
                 hide_n = 2,
                 exponentiate = TRUE)
```

# Univariate Models - 120 day delays
```{r echo=FALSE}
tbl_uvregression(data=data[c("path_treatment_120", "enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")],
                 method = glm, 
                 y = path_treatment_120,
                 method.args=list(family=binomial),
                 include = uni_predictors,
                 hide_n = 2,
                 exponentiate = TRUE)
```

# Univariate Models - 150 day delays
```{r echo=FALSE}
tbl_uvregression(data=data[c("path_treatment_150", "enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")],
                 method = glm, 
                 y = path_treatment_150,
                 method.args=list(family=binomial),
                 include = uni_predictors,
                 hide_n = 2,
                 exponentiate = TRUE)
```

# Univariate Models - 180 day delays
```{r echo=FALSE}
tbl_uvregression(data=data[c("path_treatment_180", "enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")],
                 method = glm, 
                 y = path_treatment_180,
                 method.args=list(family=binomial),
                 include = uni_predictors,
                 hide_n = 2,
                 exponentiate = TRUE)
```