---
title: "Survival Analysis (Cox)"
author: "Jessica George"
date: "10/17/2021"
output:
  html_document: default
  pdf_document: default
---

# Libraries
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(finalfit)
library(lubridate)
library(survival)
library(readxl)

source("../format_data.R")
```

# Data
```{r message=FALSE, warning=FALSE, include=FALSE}
original <- read_excel("../../data/time_to_treatment_data.xlsx") %>% 
  format_data(article_number = 3)

# grab RT/CRT patients only
data <- original %>% filter(rt == "Yes" | crt == "Yes")
```

# Univariate Results
```{r}
run_univariate <- function(data, additional_predictors=c()) {
  dependent <- "Surv(time_alive_treat, vital_status)"
  
  uni_predictors <- c("enroll_age", "age_cat", "marital", "distance_factored2", "init_performance_status", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "cr_result", "cr_result_s100", "hb_result", "wbc_result", "wbc_result_s100", "neut_result", "neut_result_s100", "alb_result", "alb_result_s100", "combined_cancer_stage", "combined_cancer_stage2", "combined_cancer_stage3", "total_chemo_received_cat", "total_chemo_received_4", "chemo", "eqd2", "eqd2_75", "eqd2_79", "eqd2_80", "pathology_group", "pathology_group2", "pathology_group3", "cancer_screening", "treat_response", "hiv_cd4_cat", "hiv_cd4_cat2")
  
  uni_predictors <- c(uni_predictors, additional_predictors)
  
  data %>%
    finalfit(dependent, uni_predictors) %>%
    select("Dependent: Surv(time_alive_treat, vital_status)", " ", "all", "HR (univariable)") %>% 
    knitr::kable()
}
```


# Overall Survival
```{r}
data %>% run_univariate(c("path_treatment_30", "path_treatment_60", "path_treatment_90", "path_treatment_120", "path_treatment_150", "path_treatment_180"))
```

# Subgroup analysis (>=30 day delays) OS
```{r}
data %>% filter(path_treatment_30 == ">=30") %>% run_univariate()
```

# Subgroup analysis (>=60 day delays) OS
```{r}
data %>% filter(path_treatment_60 == ">=60") %>% run_univariate()
```

# Subgroup analysis (>=90 day delays) OS
```{r}
data %>% filter(path_treatment_90 == ">=90") %>% run_univariate()
```

# Subgroup analysis (<90 day delays) OS
```{r}
data %>% filter(path_treatment_90 == "<90") %>% run_univariate()
```

# Subgroup analysis (>=120 day delays) OS
```{r}
data %>% filter(path_treatment_120 == ">=120") %>% run_univariate()
```

# Subgroup analysis (>=150 day delays) OS
```{r}
data %>% filter(path_treatment_150 == ">=150") %>% run_univariate()
```

# Subgroup analysis (>=180 day delays) OS
```{r}
data %>% filter(path_treatment_180 == ">=180") %>% run_univariate()
```

