---
title: "Table 2B"
author: "Jessica George and Shawna Tuli"
date: "3/15/2021"
output: html_document
---

Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(table1)
library(survival)
library(finalfit)
library(survminer)
library(forestmodel)

# Check for collinearity using vif()
library(rms)
```

Data Creation
```{r message=FALSE, warning=FALSE}
data <- read_csv("../data/data.csv") %>% 
  filter(surgery == 0) %>% 
  mutate(
    total_chemo_received_0 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "1" = "1", "1" = "2", "1" = "3", "1" = "4", "1" = "5", "1" = "6", "1" = "7"), labels = c("0", ">0")),
    total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", "1" = "4", "1" = "5", "1" = "6", "1" = "7"), labels = c("<4", ">=4")),
    on_arv = factor(on_arv, levels = c(0, 1), labels = c("Not on ARV", "On ARV")),
    combined_cancer_stage = factor(combined_cancer_stage, levels = c(1, 2, 3, 4), labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB)", "IV")),
    age_cat <- factor(age_cat, levels = c(1, 2, 3), labels = c("21-39", "40-59", ">60")),
    time_alive_years = time_alive/365
  )

label(data$age_cat) <- "Age"
label(data$cr_result) <- "Baseline Cr"
label(data$hb_result) <- "Baseline Hb"
label(data$eqd2) <- "EQD2"
label(data$vl_final) <- "Baseline VL"
label(data$cd4_final) <- "Baseline CD4"
label(data$total_chemo_received_0) <- "No. of chemo cycles received"
label(data$total_chemo_received_4) <- "No. of chemo cycles received"
label(data$combined_cancer_stage) <- "Disease stage"
label(data$on_arv) <- "On ARV"
label(data$nnrti) <- "NNRTI"
label(data$pi) <- "PI"
label(data$nrti) <- "NRTI"
label(data$dolutegravir) <- "DTG"

hiv_pos <- data %>% 
  filter(hiv_status == 1)
```

Test Cox models for HIV specific factors
```{r}
# Chemo only
explanatory1 <- c("age_cat", "combined_cancer_stage", "total_chemo_received_4", "eqd2", "cd4_final", "vl_final", "nnrti", "pi", "dolutegravir", "nrti")

# Chemo and HB
explanatory2 <- c("age_cat", "hb_result", "combined_cancer_stage", "total_chemo_received_4", "eqd2", "cd4_final", "vl_final", "nnrti", "pi", "dolutegravir", "nrti")

# Chemo and CR
explanatory3 <- c("age_cat", "cr_result", "combined_cancer_stage", "total_chemo_received_4", "eqd2", "cd4_final", "vl_final", "nnrti", "pi", "dolutegravir", "nrti")

dependent <- "Surv(time_alive, vital_status)"

hiv_pos %>% 
  finalfit(dependent, explanatory1) %>% 
  knitr::kable()

hiv_pos %>% 
  finalfit(dependent, explanatory2) %>% 
  knitr::kable()

hiv_pos %>% 
  finalfit(dependent, explanatory3) %>% 
  knitr::kable()
```

Table 2B
```{r fig.width = 10, fig.height = 7}
hiv_pos <- hiv_pos %>% 
  mutate(
    "Disease stage" = combined_cancer_stage,
    "No. of chemo cycles received" = total_chemo_received_4,
    "On ARV" = on_arv
  )

hiv_model1 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final + vl_final + nnrti + pi + dolutegravir + nrti, data = hiv_pos)

forestmodel::forest_model(hiv_model1)

hiv_model2 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + hb_result + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final + vl_final + nnrti + pi + dolutegravir + nrti, data = hiv_pos)

forestmodel::forest_model(hiv_model2)

hiv_model3 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + hb_result + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final +  + nnrti + pi + dolutegravir + nrti, data = hiv_pos)
AIC(hiv_model3)

forestmodel::forest_model(hiv_model3)

hiv_model4 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final + vl_final, data = hiv_pos)

forestmodel::forest_model(hiv_model4)
```

```{r fig.width = 10, fig.height = 7}
data_combined34stage <- hiv_pos %>% 
  mutate(`Disease stage` = factor(`Disease stage`, levels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB)", "IV"), labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III-IV (IIIA, IIIB, IV)", "III-IV (IIIA, IIIB, IV)")))

hiv_model1 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final + vl_final + nnrti + pi + dolutegravir + nrti, data = data_combined34stage)

forestmodel::forest_model(hiv_model1)

hiv_model2 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + hb_result + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final + vl_final + nnrti + pi + dolutegravir + nrti, data = data_combined34stage)

forestmodel::forest_model(hiv_model2)

hiv_model3 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + hb_result + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final +  + nnrti + pi + dolutegravir + nrti, data = data_combined34stage)
AIC(hiv_model3)

forestmodel::forest_model(hiv_model3)

hiv_model4 <- coxph(Surv(time_alive_years, vital_status) ~ age_cat + `Disease stage` + `No. of chemo cycles received` + eqd2 + cd4_final + vl_final, data = data_combined34stage)

forestmodel::forest_model(hiv_model4)
```



