format_data <- function(clean_data, article_number) {
  #'Function formats the data for a given article
  #'Current articles: 1, 2, 3, or 4
  #'Input: data (dataframe), article_number(int)
  #'Output: Returns formatted data
  if (article_number == 1) {
    formatted_data <- clean_data %>% 
      filter(!is.na(hiv_status)) %>% 
      mutate(
        hiv_status = factor(hiv_status, 
                            levels = c(1, 0), 
                            labels = c("HIV-infected", "HIV-uninfected")),
        age_cat = factor(age_cat, 
                         levels = c(1, 2, 3), 
                         labels = c("21-39", "40-59", ">60")),
        marital = factor(marital, 
                         levels = c(3, 1, 2), 
                         labels = c("Single", "Married/partnered", "Divorced/widowed")),
        cancer_screening = factor(cancer_screening, 
                                  levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        combined_cancer_stage_exact_factored = factor(combined_cancer_stage_exact, 
                                                      levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15), 
                                                      labels = c("I (A)", "I (A)", "I (A)", "I (B)", "I (B)", "I (B)", 
                                                                 "II (IIA / IIB)", "II (IIA / IIB)", "III (IIIA / IIIB / IIIC)", 
                                                                 "III (IIIA / IIIB / IIIC)", "IV (IVA / IVB)", "IV (IVA / IVB)", 
                                                                 "I (B)", "III (IIIA / IIIB / IIIC)")),
        vaginal_hemorrhage_symp = factor(vaginal_hemorrhage_symp, 
                                         levels = c(0, 1), 
                                         labels = c("No", "Yes")),
        vaginal_discharge_symp = factor(vaginal_discharge_symp, 
                                        levels = c(0, 1), 
                                        labels = c("No", "Yes")),
        pelvic_pain_symp = factor(pelvic_pain_symp, 
                                  levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1, 
                                                   as.numeric(init_performance_status) < 90 ~ 0), 
                                         levels = c(1, 0), labels = c(">=90", "<90")),
        cd4_pos_cat = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 3), 
                             levels = c(1, 2, 3), labels = c(">=500", ">=350-<500", "<350")),
        cd4_pos_cat2 = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 4), 
                              levels = c(1, 2, 3, 4), 
                              labels = c(">=500", ">=350-<500", ">=200-<350", "<200")),
        on_arv = factor(on_arv, levels = c(0, 1), labels = c("No", "Yes")),
        chemo = factor(chemo, levels = c(0, 1), labels = c("0", ">=1")),
        ebrt_40 = factor(case_when(ebrt_curr_dose >= 40 ~ 1, 
                                   ebrt_curr_dose < 40 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        brachy_cat = factor(ifelse(brachy_curr_dose > 0, 1, 0), 
                            levels = c(0, 1), labels = c("No", "Yes")),
        eqd2_75 = factor(case_when(eqd2 >= 75 ~ 1,
                                   eqd2 < 75 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        treat_response = factor(as.numeric(treat_response), 
                                levels = c(1, 2, 5), 
                                labels = c("Complete", "Partial", "Not available")),
        vl_detect = factor(case_when(vl_final < 400 ~ 0,
                                     vl_final >= 400 ~ 1), 
                           levels = c(0, 1), labels = c("Undetectable", "Detectable")),
        vl_detect2 = relevel(factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                              hiv_status == "HIV-infected" & vl_final < 400 ~ 2,
                                              hiv_status == "HIV-infected" & vl_final >= 400 ~ 3,
                                              hiv_status == "HIV-infected" & is.na(vl_final) ~ 4), levels = c(1,2,3,4), labels = c("HIV-", "Undetectable", "Detectable", "Unknown")), ref = "HIV-"),
        vl_detect_cat = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                         hiv_status == "HIV-infected" & vl_final < 400 ~ 2,
                                         hiv_status == "HIV-infected" & vl_final >= 400 ~ 3), 
                               levels = c(1,2,3), labels = c("HIV-", "Undetectable", "Detectable")),
        surgery = factor(surgery, levels = c(0, 1), labels = c("No", "Yes")),
        total_chemo_received_cat = factor(case_when(total_chemo_received == 0 ~ 0,
                                                    total_chemo_received == 1 ~ 1,
                                                    total_chemo_received == 2 ~ 2,
                                                    total_chemo_received == 3 ~ 3,
                                                    total_chemo_received >= 4 ~ 4),
                                          levels = c(0,1,2,3,4), 
                                          labels = c("0", "1", "2", "3", ">=4")),
        total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", 
                                                            "1" = "4", "1" = "5", "1" = "6", "1" = "7"), 
                                        labels = c("<4", ">=4")),
        pathology_year = year(ymd(pathology_date)),
        # HIV- then HIV+ increasing with CD4
        hiv_cd4_cat = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 500 ~ 4,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 3,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 2),
                             levels = c(1, 2, 3, 4), 
                             labels = c("HIV-", "<350", ">=350-<500", ">=500")),
        # HIV- then HIV+ increasing with CD4
        hiv_cd4_cat2 = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 500 ~ 5, 
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 4,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 2), 
                              levels = c(1, 2, 3, 4, 5), 
                              labels = c("HIV-","<200", ">=200-<350", ">=350-<500", ">=500")),
        # 0 if no treatment, 1 if treatment
        treatment = factor(treatment, levels = c(0,1), labels = c("No", "Yes")),
        # 0 if no RT, 1 if RT received
        rt_received = factor(ifelse(eqd2 > 0, 1, 0), 
                             levels = c(0,1), labels = c("No", "Yes")),
        time_alive_path = time_alive_path/365)
  }
  
  else if (article_number == 2) {
    formatted_data <- clean_data %>% 
      filter(surgery == 0 & primary_surgery == 0 & combined_cancer_stage_exact >= 5) %>% 
      mutate(
        hiv_status = relevel(factor(hiv_status, 
                            levels = c(1, 0), 
                            labels = c("HIV-infected", "HIV-uninfected")), ref = "HIV-uninfected"),
        age_cat = factor(age_cat, levels = c(1, 2, 3), 
                         labels = c("21-39", "40-59", ">60")),
        marital = factor(marital, levels = c(3, 1, 2), 
                         labels = c("Single", "Married/partnered", "Divorced/widowed")),
        cancer_screening = factor(cancer_screening, levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        combined_cancer_stage = factor(combined_cancer_stage, levels = c(1, 2, 3, 4),
                                       labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III-IV (IIIA, IIIB, IV)", "III-IV (IIIA, IIIB, IV)")),
        vaginal_hemorrhage_symp = factor(vaginal_hemorrhage_symp, levels = c(0, 1),
                                         labels = c("No", "Yes")),
        vaginal_discharge_symp = factor(vaginal_discharge_symp, levels = c(0, 1), 
                                        labels = c("No", "Yes")),
        pelvic_pain_symp = factor(pelvic_pain_symp, levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1,
                                                   as.numeric(init_performance_status) < 90 ~ 0), levels = c(1, 0), labels = c(">=90", "<90")),
        cd4_pos_cat = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 3), 
                             levels = c(1, 2, 3), 
                             labels = c(">=500", ">=350-<500", "<350")),
        cd4_pos_cat2 = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 4), levels = c(1, 2, 3, 4), 
                              labels = c(">=500", ">=350-<500", ">=200-<350", "<200")),
        on_arv = factor(on_arv, levels = c(0, 1), labels = c("No", "Yes")),
        chemo = factor(chemo, levels = c(0, 1), labels = c("0", ">=1")),
        ebrt_40 = factor(case_when(ebrt_curr_dose >= 40 ~ 1, 
                                   ebrt_curr_dose < 40 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        brachy_20 = factor(case_when(brachy_curr_dose >= 20 ~ 1, 
                                     brachy_curr_dose < 20 ~ 0), 
                           levels = c(0, 1), labels = c("No", "Yes")),
        eqd2_75 = factor(case_when(eqd2 >= 75 ~ 1,
                                   eqd2 < 75 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        treat_response = factor(as.numeric(treat_response), 
                                levels = c(1, 2, 5), 
                                labels = c("Complete", "Partial", "Not available")),
        vl_detect = factor(case_when(vl_final < 400 ~ 0,
                                     vl_final >= 400 ~ 1), 
                           levels = c(0, 1), labels = c("Undetectable", "Detectable")),
        total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", 
                                                            "1" = "4", "1" = "5", "1" = "6", "1" = "7"), labels = c("<4", ">=4")))
  }
  
  else if (article_number == 3) {
    formatted_data <- clean_data %>% 
      # Filter out patients without treatment start date (87) and patients who have negative time to treatment
      filter(!is.na(actual_treat_start_date) & path_to_treatment_difference >= 0) %>% 
      mutate(   
        age_cat = factor(age_cat, levels = c(1, 2, 3), labels = c("21-39", "40-59", ">60")),
        marital = factor(marital, levels = c(3, 1, 2), labels = c("Single", "Married/partnered", "Divorced/widowed")),
        init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1, 
                                                   as.numeric(init_performance_status) < 90 ~ 0), levels = c(1, 0), labels = c(">=90", "<90")),
        combined_cancer_stage = factor(combined_cancer_stage, levels = c(1, 2, 3, 4), labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB, IIC)", "IV (IVA, IVB)")),
        total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", "1" = "4", "1" = "5", 
                                                            "1" = "6", "1" = "7"), labels = c("<4", ">=4")),
        total_chemo_received_cat = factor(case_when(total_chemo_received == 0 ~ 0,
                                                    total_chemo_received == 1 ~ 1,
                                                    total_chemo_received == 2 ~ 2,
                                                    total_chemo_received == 3 ~ 3,
                                                    total_chemo_received >= 4 ~ 4), levels = c(0,1,2,3,4), labels = c("0", "1", "2", "3", ">=4")),
        
        chemo = factor(chemo, levels = c(0, 1), labels = c("0", ">=1")),
        ebrt_40 = factor(case_when(ebrt_curr_dose >= 40 ~ 1, 
                                   ebrt_curr_dose < 40 ~ 0), levels = c(0, 1), labels = c("No", "Yes")),
        brachy_20 = factor(case_when(brachy_curr_dose >= 20 ~ 1, 
                                     brachy_curr_dose < 20 ~ 0), levels = c(0, 1), labels = c("No", "Yes")),
        brachy_cat = factor(ifelse(brachy_curr_dose > 0, 1, 0), levels = c(0, 1), labels = c("No", "Yes")),
        eqd2_75 = factor(case_when(eqd2 >= 75 ~ 1,
                                   eqd2 < 75 ~ 0), levels = c(0, 1), labels = c("No", "Yes")),
        # HIV- then HIV+ increasing with CD4
        hiv_cd4_cat = factor(case_when(hiv_status == 0 ~ 1,
                                       hiv_status == 1 & cd4_final >= 500 ~ 4, 
                                       hiv_status == 1 & cd4_final >= 350 & cd4_final < 500 ~ 3,
                                       hiv_status == 1 & cd4_final < 350 ~ 2), levels = c(1, 2, 3, 4), 
                             labels = c("HIV-", "<350", ">=350-<500", ">=500")),
        # HIV- then HIV+ increasing with CD4
        hiv_cd4_cat2 = factor(case_when(hiv_status == 0 ~ 1,
                                        hiv_status == 1 & cd4_final >= 500 ~ 5, 
                                        hiv_status == 1 & cd4_final >= 350 & cd4_final < 500 ~ 4,
                                        hiv_status == 1 & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == 1 & cd4_final < 200 ~ 2), levels = c(1, 2, 3, 4, 5), 
                              labels = c("HIV-","<200", ">=200-<350", ">=350-<500", ">=500")),
        path_treatment_90 = factor(ifelse(path_to_treatment_difference < 90, 0, 1), levels = c(0,1), labels=c("<90", ">=90")),
        path_treatment_120 = factor(ifelse(path_to_treatment_difference < 120, 0, 1), levels = c(0,1), labels=c("<120", ">=120")),
        path_treatment_150 = factor(ifelse(path_to_treatment_difference < 150, 0, 1), levels = c(0,1), labels=c("<150", ">=150")),
        path_treatment_180 = factor(ifelse(path_to_treatment_difference < 180, 0, 1), levels = c(0,1), labels=c("<180", ">=180")),
        path_treatment_group = factor(case_when(path_to_treatment_difference < 90 ~ 1,
                                                path_to_treatment_difference >= 90 & path_to_treatment_difference < 150 ~ 2,
                                                path_to_treatment_difference >= 150 ~ 3), levels=c(1,2,3), labels=c("<90", ">=90-<150", ">=150")),
        pathology_year = year(ymd(pathology_date)),
        rt_received = factor(ifelse(eqd2 > 0, 1, 0), levels = c(0,1), labels = c("No", "Yes")),
        vl_detect = factor(case_when(vl_final < 400 ~ 0,
                                     vl_final >= 400 ~ 1), levels = c(0, 1), labels = c("Undetectable", "Detectable")),
        pathology_group = factor(case_when(pathology_year < 2016 ~ 2015,
                                           pathology_year == 2016 ~ 2016,
                                           pathology_year == 2017 ~ 2017,
                                           pathology_year == 2018 ~ 2018,
                                           pathology_year == 2019 ~ 2019),
                                 levels=c(2015, 2016, 2017, 2018, 2019), labels=c("<2016", "2016", "2017", "2018", "2019")))
  }

  else {
    print("Function expects data and article number: Returning NULL")
    return(NULL)
  }
  return(formatted_data)
}