---
title: "Survival Curves"
author: "Jessica George and Shawna Tuli"
date: "12/27/2020"
output: html_document
---

Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(survival)
library(finalfit)
library(survminer)
library(forestmodel)

# Check for collinearity using vif()
library(rms)
```

Data Creation
```{r message=FALSE, warning=FALSE}
data <- read_csv("../data/data.csv") %>% 
  mutate(
    hiv_status = factor(hiv_status, levels = c(0, 1), labels = c("HIV-uninfected", "HIV-infected")),
    combined_cancer_stage = factor(combined_cancer_stage, levels = c(1, 2, 3, 4), labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB)", "IV (IVA, IVB)")),
    time_alive = time_alive/365)
```

KMs on All Patients
1) Survival status by stage
```{r, fig.height = 7, fig.width = 8}
data_for_curve <- data %>% 
  filter(time_alive < 7)
stage_survival <- survfit(Surv(time_alive, vital_status) ~ combined_cancer_stage, data_for_curve) 

stage_plot <- ggsurvplot(fit = stage_survival,
  data_for_curve,
  xlab = "Years since first day of chemoradiation",
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by Cancer Stage",
  break.time.by = 1,
  palette = c("darkred", "red", "blue", "darkblue"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB)", "IV"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
stage_plot$plot <- stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = -10))
stage_plot$table <- stage_plot$table + theme(plot.title = element_text(hjust = -0.2, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))
stage_plot
```

2) Survival status by HIV status and stage
```{r, fig.height = 9, fig.width = 10}
data_for_curve <- data %>% 
  filter(time_alive < 7)
hiv_stage_survival <- survfit(Surv(time_alive, vital_status) ~ hiv_status + combined_cancer_stage, data_for_curve) 

hiv_stage_plot <- ggsurvplot(fit = hiv_stage_survival,
  data_for_curve,
  xlab = "Years since first day of chemoradiation",
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by HIV Status and Cancer Stage",
  break.time.by = 1,
  palette = c("darkred", "red", "darkblue", "blue", "darkorange", "orange", "magenta", "purple"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("HIV-, I (IB1*, IB2)", "HIV-, II (IIA, IIB)",
                  "HIV-, III (IIIA, IIIB, IIIC)", "HIV-, IV (IVA, IVB)",
                  "HIV+, I (IB1*, IB2)", "HIV+, II (IIA, IIB)",
                  "HIV+, III (IIIA, IIIB, IIIC)", "HIV+, IV (IVA, IVB)"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
hiv_stage_plot$plot <- hiv_stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = -30))
hiv_stage_plot$table <- hiv_stage_plot$table + theme(plot.title = element_text(hjust = -0.28, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))
hiv_stage_plot
```

KMs on Non-Surgery Patients
1) Survival by HIV status -- Non-surgery
```{r}
# hiv_survival <- survfit(Surv(time_alive, vital_status) ~ hiv_status, non_surgery_patients)
# 
# hiv_plot <- ggsurvplot(fit = hiv_survival,
#   non_surgery_patients,
#   xlab = "Years since first day of chemoradiation", 
#   ylab = "Proportion surviving",
#   title = "Kaplan-Meier Survival Estimates by HIV Status",
#   break.time.by = 1,
#   palette = c("#0000FF", "#FF0000"),
#   conf.int = FALSE,
#   censor = TRUE,
#   legend.title="",
#   legend.labs = c("HIV-uninfected", "HIV-infected"),
#   risk.table = TRUE,
#   risk.table.height = 0.2,
#   tables.theme = theme_cleantable())
# hiv_plot$plot <- hiv_plot$plot +
#   theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = -15))
# hiv_plot$table <- hiv_plot$table + theme(plot.title = element_text(hjust = -0.33, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))
# hiv_plot
```

2) Survival by chemoradiation therapy -- Non-surgery
```{r}
# chemo_rad_survival <- survfit(Surv(time_alive, vital_status) ~ chemo_rad, non_surgery_patients)
# 
# chemo_rad_plot <- ggsurvplot(fit = chemo_rad_survival,
#   non_surgery_patients,
#   xlab = "Years since first day of chemoradiation", 
#   ylab = "Proportion surviving",
#   title = "Kaplan-Meier Survival Estimates by CRT",
#   break.time.by = 1,
#   palette = c("#0000FF", "#FF0000"),
#   conf.int = FALSE,
#   censor = TRUE,
#   legend.title = "",
#   legend.labs = c("CRT", "RT"),
#   risk.table = TRUE,
#   risk.table.height = 0.2,
#   tables.theme = theme_cleantable())
# chemo_rad_plot$plot <- chemo_rad_plot$plot +
#   theme(plot.title = element_text(hjust = 0.5), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))
# chemo_rad_plot$table <- chemo_rad_plot$table + theme(plot.title = element_text(hjust = -0.12, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))
# chemo_rad_plot
```

3) Survival by HIV status and chemoradiation therapy
```{r}
# hiv_chemo_rad_survival <- survfit(Surv(time_alive, vital_status) ~ hiv_status + chemo_rad, non_surgery_patients)
# 
# hiv_chemo_rad_plot <- ggsurvplot(fit = hiv_chemo_rad_survival,
#   non_surgery_patients,
#   xlab = "Years since first day of chemoradiation", 
#   ylab = "Proportion surviving",
#   title = "Kaplan-Meier Survival Estimates by HIV Status & CRT",
#   break.time.by = 1,
#   palette = c("darkred", "red", "blue", "darkblue"),
#   conf.int = FALSE,
#   censor = TRUE,
#   legend.title = "",
#   legend.labs = c("HIV+&CRT", "HIV+&RT", "HIV-&CRT", "HIV-&RT"),
#   risk.table = TRUE,
#   risk.table.height = 0.3,
#   tables.theme = theme_cleantable())
# hiv_chemo_rad_plot$plot <- hiv_chemo_rad_plot$plot +
#   theme(plot.title = element_text(hjust = 0.7), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = -10))
# hiv_chemo_rad_plot$table <- hiv_chemo_rad_plot$table + theme(plot.title = element_text(hjust = -0.24, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))
# hiv_chemo_rad_plot
```