---
title: "Table A: Demographics by HIV Status"
author: "Jessica George and Shawna Tuli"
date: "01/21/22"
output: 
  html_document:
    toc: True
    toc_depth: 2
---

# Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
# library(Table1)
library(gtsummary)
library(lubridate)

source("../format_data.R")
```


# Data
```{r message=FALSE, warning=FALSE}
all_patients <- read_csv("../../data/data.csv") %>% 
  format_data(article_number = 1)
```


# Table A
```{r}
# Skipping HIV-related variables: cd4_final, cd4_pos_cat, cd4_pos_cat2, on_arv, vl_detect... See below for calculations for these variables


all_patients %>% 
  select("hiv_status", "age_cat", "marital", "cancer_screening", "distance_factored2", "combined_cancer_stage_exact_factored2", "vaginal_hemorrhage_symp", "vaginal_discharge_symp", "pelvic_pain_symp", "init_performance_status", "treat_response", "surgery_only", "rt", "chemo_only",  "crt", "primary_surgery_chemo", "primary_surgery_rt", "primary_surgery_crt", "treatment", "cr_opt", "hb_opt", "neut_opt",  "wbc_opt", "alb_opt", "enroll_age", "cr_result", "hb_result", "neut_result", "wbc_result", "alb_result") %>% 
  tbl_summary(
    by = hiv_status,
    missing = "no"
  ) %>% 
  add_n() %>% 
  add_p(pvalue_fun = ~style_sigfig(., digits = 4))

# Cr
all_patients %>% 
  group_by(hiv_status) %>% 
  summarise(quantile(cr_result, 0.25, na.rm=TRUE), quantile(cr_result, 0.75, na.rm=TRUE))

# ANC
all_patients %>% 
  group_by(hiv_status) %>% 
  summarise(quantile(neut_result, 0.25, na.rm=TRUE), quantile(neut_result, 0.75, na.rm=TRUE))

# Alb
all_patients %>% 
  group_by(hiv_status) %>% 
  summarise(quantile(alb_result, 0.25, na.rm=TRUE), quantile(alb_result, 0.75, na.rm=TRUE))

# cd4_final
# median
sapply(select(filter(all_patients, hiv_status == "HIV-infected"), cd4_final), median, na.rm = T)
# quantiles
quantile(select(filter(all_patients, hiv_status == "HIV-infected"), cd4_final), probs = c(0.25, 0.75), na.rm = T)

# cd4_pos_cat
# counts
all_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(cd4_pos_cat) %>% summarise(n())

# cd4_pos_cat2
# counts
all_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(cd4_pos_cat2) %>% summarise(n())

# vl_final
# mean
sapply(select(filter(all_patients, hiv_status == "HIV-infected"), vl_final), median, na.rm = T)
# quantiles
quantile(select(filter(all_patients, hiv_status == "HIV-infected"), vl_final), probs = c(0.25, 0.75), na.rm = T)

# on_arv
all_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(on_arv) %>% summarise(n())

# vl_detect
all_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(vl_detect) %>% summarise(n())
```