---
title: "Kaplan-Meier Survival Curves"
author: "Jessica George and Shawna Tuli"
date: "01/20/22"
output: 
  html_document:
    toc: True
    toc_depth: 2
---

# Libraries
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(survival)
library(survminer)
library(DescTools)
library(patchwork)
library(lubridate)

source("../format_data.R")
```


# Data
```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- read_csv("../../data/data.csv") %>% 
  format_data(article_number = 1)
```


# KMs on All Patients
## 1) Survival status by stage
```{r echo=TRUE, fig.width=8, message=FALSE, warning=FALSE}
stage_survival <- survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact_factored2, data)

stage_plot <- ggsurvplot(fit = stage_survival,
                         data,
                         xlab = "Years since pathology report",
                         xlim = c(0, 6),
                         ylab = "Proportion surviving",
                         title = "Kaplan-Meier Survival Estimates by Cancer Stage",
                         break.time.by = 1,
                         palette = c("#333333", "#E69F00", 
                                     "#009E73", "#56B4E9", "#0072B2"),
                         conf.int = FALSE,
                         censor = TRUE,
                         legend.title="",
                         legend.labs = c("I (IA, IA1, IA2)", "I (IB1*, IB2)", 
                                         "II (IIA, IIB)", 
                                         "III (IIIA, IIIB, IIIC)", 
                                         "IV (IVA, IVB)"),
                         risk.table = TRUE,
                         risk.table.height = 0.2,
                         tables.theme = theme_cleantable())

stage_plot$plot <- stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), 
        panel.grid.major.y = element_line(color = "#EAF2F3"), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        axis.title.y = element_text(vjust = 1))

stage_plot$plot
```
```{r echo=TRUE, fig.height=2, fig.width=8, message=FALSE, warning=FALSE}
stage_plot$table <- stage_plot$table + 
  theme(plot.title = element_text(hjust = -0.25, size = 14), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        panel.background = element_rect(fill = "#EAF2F3"))

stage_plot$table
```


## 2) Survival status by HIV status and stage
```{r echo=TRUE, fig.width=8, message=FALSE, warning=FALSE}
hiv_stage_survival <- survfit(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact_factored2, data)

hiv_stage_plot <- ggsurvplot(fit = hiv_stage_survival,
                             data,
                             xlab = "Years since pathology report",
                             xlim = c(0, 6),
                             ylab = "Proportion surviving",
                             title = "Kaplan-Meier Survival Estimates by HIV Status and Cancer Stage",
                             break.time.by = 1,
                             color = "hiv_status",
                             palette = c("#56B4E9", "#0072B2"),
                             conf.int = FALSE,
                             censor = TRUE,
                             legend.title="",
                             risk.table = TRUE,
                             risk.table.height = 0.2,
                             tables.theme = theme_cleantable())

hiv_stage_plot$plot <- hiv_stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), 
        panel.grid.major.y = element_line(color = "#EAF2F3"), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        axis.title.y = element_text(vjust = 1))

hiv_stage_plot$plot +
  facet_wrap(~ combined_cancer_stage_exact_factored2)
```
```{r echo=TRUE, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}
hiv_stage_plot$table <- hiv_stage_plot$table + 
  theme(plot.title = element_text(hjust = -0.08, size = 14), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        panel.background = element_rect(fill = "#EAF2F3"))

hiv_stage_plot$table
```


## 3) Combined survival plot: Survival Curve for RT Y/N, Surgery Y/N, and Treatment Y/N
```{r echo=TRUE, message=FALSE, warning=FALSE}
# RT Y/N Curve
rt_survival <- survfit(Surv(time_alive_path, vital_status) ~ rt_received, data)

rt_plot <- ggsurvplot(fit = rt_survival,
                      data,
                      xlab = "",
                      xlim = c(0, 6),
                      ylab = "",
                      title = "Kaplan-Meier Survival Estimates by RT Receipt",
                      break.time.by = 1,
                      palette = c("#56B4E9", "#0072B2"),
                      conf.int = FALSE,
                      censor = TRUE,
                      legend.title="",
                      legend.labs = c("No", "Yes"),
                      #risk.table = TRUE,
                      risk.table = FALSE,
                      #risk.table.height = 0.2,
                      tables.theme = theme_cleantable())

rt_plot$plot <- rt_plot$plot +
  theme(plot.title = element_text(size = 14, hjust = 0.4), 
        panel.grid.major.y = element_line(color = "#EAF2F3"), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        axis.title.y = element_text(vjust = 1), 
        axis.text.x = element_text(size = 11), 
        axis.text.y = element_text(size = 11))

# Surgery Y/N Curve
surgery_survival <- survfit(Surv(time_alive_path, vital_status) ~ surgery, data)

surgery_plot <- ggsurvplot(fit = surgery_survival,
                           data,
                           xlab = "",
                           xlim = c(0, 6),
                           ylab = "Proportion surviving",
                           title = "Kaplan-Meier Survival Estimates by Surgery Receipt",
                           break.time.by = 1,
                           palette = c("#56B4E9", "#0072B2"),
                           conf.int = FALSE,
                           censor = TRUE,
                           legend.title="",
                           legend.labs = c("No", "Yes"),
                           #risk.table = TRUE,
                           risk.table = FALSE,
                           #risk.table.height = 0.2,
                           tables.theme = theme_cleantable())

surgery_plot$plot <- surgery_plot$plot +
  theme(plot.title = element_text(size = 14, hjust = 0.4), 
        panel.grid.major.y = element_line(color = "#EAF2F3"), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        axis.title.y = element_text(size = 13, vjust = 1, hjust = 0.45), 
        axis.text.x = element_text(size = 11), 
        axis.text.y = element_text(size = 11))

# Treatment Y/N Curve
treatment_survival <- survfit(Surv(time_alive_path, vital_status) ~ treatment, data)

treatment_plot <- ggsurvplot(fit = treatment_survival,
                             data,
                             xlab = "Years since pathology report",
                             xlim = c(0, 6),
                             ylab = "",
                             title = "Kaplan-Meier Survival Estimates by Treatment Receipt",
                             break.time.by = 1,
                             palette = c("#56B4E9", "#0072B2"),
                             conf.int = FALSE,
                             censor = TRUE,
                             legend.title="",
                             legend.labs = c("No", "Yes"),
                             #risk.table = TRUE,
                             risk.table = FALSE,
                             #risk.table.height = 0.2,
                             tables.theme = theme_cleantable())

treatment_plot$plot <- treatment_plot$plot +
  theme(plot.title = element_text(size = 14, hjust = 0.4), 
        panel.grid.major.y = element_line(color = "#EAF2F3"), 
        plot.background = element_rect(fill = "#EAF2F3"), 
        axis.title.x = element_text(size = 13), 
        axis.text.x = element_text(size = 11), 
        axis.text.y = element_text(size = 11))

(rt_plot$plot/surgery_plot$plot/treatment_plot$plot) / guide_area() +
  plot_layout(guides = 'collect')
```
```{r echo=TRUE, message=FALSE, warning=FALSE}
# plotting separately
rt_plot$plot
surgery_plot$plot
treatment_plot$plot
```


# Log Rank Tests on Survival Curves above
```{r echo=TRUE, message=FALSE, warning=FALSE}
# plot 1: survival by stage
surv_diff1 <- survdiff(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact_factored2, data)
surv_diff1

# plot 2: survival by HIV status and stage
surv_diff2 <- survdiff(Surv(time_alive_path, vital_status) ~ factor(hiv_status) + factor(combined_cancer_stage_exact_factored2), data)
surv_diff2

# plot 3:
## a) RT Y/N
surv_diff3a <- survdiff(Surv(time_alive_path, vital_status) ~ rt_received, data)
surv_diff3a
## b) Surgery Y/N
surv_diff3b <- survdiff(Surv(time_alive_path, vital_status) ~ surgery, data)
surv_diff3b
## c) Treatment Y/N
surv_diff3c <- survdiff(Surv(time_alive_path, vital_status) ~ treatment, data)
surv_diff3c
```


```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Unused plot: Survival Curve for RT/CRT eligible vs. Surgery eligible
# # Grab patients
# rt_crt_eligible <- data %>%
#   filter(combined_cancer_stage_exact >= 4) %>%
#   filter(surgery == "No" | is.na(surgery)) %>%
#   mutate(group = "RT/CRT Eligible")
# 
# surgery <- data %>%
#   filter(combined_cancer_stage_exact < 4 | (combined_cancer_stage_exact >= 4 & surgery == "Yes"))  %>%
#   mutate(group = "Surgery Eligible")
# 
# # Combine groups
# curve3_patients <- rbind(rt_crt_eligible, surgery)
# 
# # Make curve
# rt_surgery_survival <- survfit(Surv(time_alive_path, vital_status) ~ group, curve3_patients)
# 
# rt_surgery_plot <- ggsurvplot(fit = rt_surgery_survival,
#   curve3_patients,
#   xlab = "Years since pathology report",
#   xlim = c(0, 6),
#   ylab = "Proportion surviving",
#   title = "Kaplan-Meier Survival Estimates by Treatment Group",
#   break.time.by = 1,
#   palette = c("#56B4E9", "#0072B2"),
#   conf.int = FALSE,
#   censor = TRUE,
#   legend.title="",
#   legend.labs = c("RT/CRT Eligible", "Surgery Eligible"),
#   risk.table = TRUE,
#   risk.table.height = 0.2,
#   tables.theme = theme_cleantable())
# rt_surgery_plot$plot <- rt_surgery_plot$plot +
#   theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))
# 
# rt_surgery_plot$plot
```


# Median Time
```{r echo=TRUE, message=FALSE, warning=FALSE}
# overall
data %>% 
  summarise(MedianCI(na.omit(time_alive_path)))
# by stage
data %>% 
  group_by(combined_cancer_stage_exact_factored3) %>%
  summarise(MedianCI(na.omit(time_alive_path)))
# by HIV status and stage
data %>% 
  group_by(hiv_status, combined_cancer_stage_exact) %>%
  summarise(MedianCI(na.omit(time_alive_path)))
# by treatment
data %>% 
  group_by(treatment) %>% 
  summarise(MedianCI(na.omit(time_alive_path)))
```


# 2-year OS
```{r echo=TRUE, message=FALSE, warning=FALSE}
# overall
summary(survfit(Surv(time_alive_path, vital_status) ~ 1, data), 
        times = c(2), extend = T)
# by HIV status 
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status, data), 
        times = c(2), extend = T)
survdiff(Surv(time_alive_path, vital_status) ~ hiv_status, data)
# by stage
summary(survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact_factored3, data), 
        times = c(2), extend = T)
survdiff(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact_factored, data)
# by HIV status and stage
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact_factored, data), 
        times = c(2), extend = T)
survdiff(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact, data)

# HIV status
data %>% 
  filter(hiv_status == "HIV-infected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ 1,.) %>%
  summary(times = c(2), extend = T)
# HIV-infected by stage
data %>% 
  filter(hiv_status == "HIV-infected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact,.) %>%
  summary(times = c(2), extend = T)
# HIV-uninfected by stage
data %>% 
  filter(hiv_status == "HIV-uninfected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact,.) %>%
  summary(times = c(2), extend = T)

# by stage
summary(survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact_factored3, data), 
        times = c(2), extend = T)

# by treatment receipt
summary(survfit(Surv(time_alive_path, vital_status) ~ treatment, data), 
        times = c(2), extend = T)
```