---
title: "Median Survival Time"
author: "Shawna Tuli and Jessica George"
date: "01/20/22"
output:
  html_document:
    toc: True
    toc_depth: 2
editor_options: 
  chunk_output_type: inline
---

# Libraries
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(survival)
library(survminer)
library(DescTools)
library(patchwork)
```


# Data
```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- read_csv("../../data/article_4_cleaned_data.csv") %>% 
  rename('HIV' = 'HIV status', 
         'Vital' = 'Vital status', 
         'Date' = 'Last Follow up date or date of death of died', 
         'VL' = 'VL at cancer diagnosis', 
         'CD4' = 'CD4 at cancer diagnosis', 
         'Cycles' = 'Cycles of chemo', 
         'Path' = 'Path response')  
```


# Median survival time
```{r}
# Filter to be patients who died
data %>% filter(Vital == 1) %>% summarize(median(date_of_death_and_start_date))
# Filter to patient who did not die
data %>% filter(Vital == 0) %>% summarize(median(date_of_death_and_start_date))
```