---
title: "Survival Curves"
author: "Jessica George and Shawna Tuli"
date: "3/15/2021"
output: html_document
---

# Libraries
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(survival)
library(survminer)
library(DescTools)
library(patchwork)

source("../format_data.R")
```

# Data
```{r message=FALSE, warning=FALSE, include=FALSE}
data <- read_csv("../../data/data.csv") %>% 
  format_data(article_number = 1)
```

# KMs on All Patients
## 1) Survival status by stage
```{r, fig.width = 8}
stage_survival <- survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact_factored, data)

stage_plot <- ggsurvplot(fit = stage_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 6),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by Cancer Stage",
  break.time.by = 1,
  palette = c("#333333", "#E69F00", "#009E73", "#56B4E9", "#0072B2"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("I (IA, IA1, IA2)", "I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB, IIIC)", "IV (IVA, IVB)"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
stage_plot$plot <- stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

stage_plot$plot
```
```{r, fig.height = 2, fig.width = 8}
stage_plot$table <- stage_plot$table + theme(plot.title = element_text(hjust = -0.25, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))

stage_plot$table
```


## 2) Survival status by HIV status and stage
```{r, fig.width = 12}
hiv_stage_survival <- survfit(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact_factored, data)

hiv_stage_plot <- ggsurvplot(fit = hiv_stage_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 6),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by HIV Status and Cancer Stage",
  break.time.by = 1,
  color = "hiv_status",
  palette = c("#56B4E9", "#0072B2"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
hiv_stage_plot$plot <- hiv_stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

hiv_stage_plot$plot +
  facet_wrap(~ combined_cancer_stage_exact_factored)
```
```{r, fig.height = 4, fig.width = 12}
hiv_stage_plot$table <- hiv_stage_plot$table + theme(plot.title = element_text(hjust = -0.08, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))

tablelabs = rev(c("HIV-uninfected", "", "", "", "", "HIV-infected", "", "", "", ""))
hiv_stage_plot$table +
  facet_wrap(~ combined_cancer_stage_exact_factored) +
  scale_y_discrete(labels = tablelabs)
```

## 3) Survival Curve for RT/CRT eligible vs. Surgery eligible
```{r}
# Grab patients
rt_crt_eligible <- data %>% 
  filter(combined_cancer_stage_exact >= 4 & surgery != "Yes") %>%
  mutate(group = "RT/CRT Eligible")

surgery <- data %>% 
  filter(combined_cancer_stage_exact < 4 | (combined_cancer_stage_exact >= 4 & surgery == "Yes")) %>% 
  mutate(group = "Surgery Eligible")

# Combine groups
curve3_patients <- rbind(rt_crt_eligible, surgery)

# Make curve
rt_surgery_survival <- survfit(Surv(time_alive_path, vital_status) ~ group, curve3_patients)

rt_surgery_plot <- ggsurvplot(fit = rt_surgery_survival,
  curve3_patients,
  xlab = "Years since pathology report",
  xlim = c(0, 6),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by Treatment Group",
  break.time.by = 1,
  palette = c("#56B4E9", "#0072B2"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("RT/CRT Eligible", "Surgery Eligible"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
rt_surgery_plot$plot <- rt_surgery_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

rt_surgery_plot$plot
```

## 4) Survival Curve for RT Y/N and Surgery Y/N
```{r}
# RT Y/N Curve
rt_survival <- survfit(Surv(time_alive_path, vital_status) ~ rt_received, data)

rt_plot <- ggsurvplot(fit = rt_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 6),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by RT Receipt",
  break.time.by = 1,
  palette = c("#56B4E9", "#0072B2"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("No", "Yes"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
rt_plot$plot <- rt_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

surgery_survival <- survfit(Surv(time_alive_path, vital_status) ~ surgery, data)

surgery_plot <- ggsurvplot(fit = surgery_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 6),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by Surgery Receipt",
  break.time.by = 1,
  palette = c("#56B4E9", "#0072B2"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("No", "Yes"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
surgery_plot$plot <- surgery_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

rt_plot$plot
surgery_plot$plot #+ plot_layout( guides = 'collect')
```

## 4) Survival Curve for Treatment
```{r}
treatment_survival <- survfit(Surv(time_alive_path, vital_status) ~ treatment, data)

treatment_plot <- ggsurvplot(fit = treatment_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 6),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates by Treatment Receipt",
  break.time.by = 1,
  palette = c("#56B4E9", "#0072B2"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("No", "Yes"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
treatment_plot$plot <- treatment_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

treatment_plot$plot
```

# Derived Survival Info
```{r eval=FALSE, include=FALSE}
## Median time
# Overall
data %>% summarise(median(time_alive_path, na.rm = T))
data %>% summarise(MedianCI(na.omit(time_alive_path)))
# By stage
data %>% group_by(combined_cancer_stage_exact) %>% dplyr::summarise(median(time_alive_path, na.rm = T))
# By HIV status
data %>% group_by(hiv_status) %>% dplyr::summarise(median(time_alive_path, na.rm = T))
data %>% group_by(hiv_status) %>% dplyr::summarise(MedianCI(na.omit(time_alive_path)))
# By HIV status and stage
data %>% group_by(hiv_status, combined_cancer_stage_exact) %>% dplyr::summarise(median(time_alive_path, na.rm = T))



## 2 year survival
# Overall
summary(survfit(Surv(time_alive_path, vital_status) ~ 1, data), times = c(2), extend = T)
# By stage
summary(survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact, data) , times = c(2), extend = T)
survdiff(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact, data)
# By HIV status
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status, data) , times = c(2), extend = T)
survdiff(Surv(time_alive_path, vital_status) ~ hiv_status, data)
# By HIV status and stage
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact, data) , times = c(2), extend = T)
survdiff(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact, data)
# HIV-infected
data %>% filter(hiv_status == "HIV-infected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ 1,.) %>% 
  summary(times = c(2), extend = T)
# HIV-infected by stage
data %>% filter(hiv_status == "HIV-infected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact,.) %>% 
  summary(times = c(2), extend = T)
# HIV-uninfected by stage
data %>% filter(hiv_status == "HIV-uninfected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact,.) %>% 
  summary(times = c(2), extend = T)
  

## 5 year survival
# Overall
summary(survfit(Surv(time_alive_path, vital_status) ~ 1, data), times = c(5), extend = T)
# By stage
summary(survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact, data) , times = c(5), extend = T)
# By HIV status
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status, data) , times = c(5), extend = T)
# By HIV status and stage
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact, data) , times = c(5), extend = T)
# HIV-infected
data %>% filter(hiv_status == "HIV-infected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ 1,.) %>% 
  summary(times = c(5), extend = T)
# HIV-infected by stage
data %>% filter(hiv_status == "HIV-infected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact,.) %>% 
  summary(times = c(5), extend = T)
# HIV-uninfected by stage
data %>% filter(hiv_status == "HIV-uninfected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ 1,.) %>% 
  summary(times = c(5), extend = T)
data %>% filter(hiv_status == "HIV-uninfected") %>%
  survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact,.) %>% 
  summary(times = c(5), extend = T)

## Alive v. dead
# Overall
summary(survfit(Surv(time_alive_path, vital_status) ~ 1, data), times = c(1,2,3,4,5,6), extend = T)$n.event
# By stage
summary(survfit(Surv(time_alive_path, vital_status) ~ combined_cancer_stage_exact, data), times = c(1,2,3,4,5,6), extend = T)$n.event
# By HIV status
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status, data), times = c(1,2,3,4,5,6), extend = T)$n.event
# By HIV status and stage
summary(survfit(Surv(time_alive_path, vital_status) ~ hiv_status + combined_cancer_stage_exact, data), times = c(1,2,3,4,5,6), extend = T)$n.event
```