---
title: "Table 2b"
author: "Jessica George and Shawna Tuli"
date: "3/15/2021"
output: html_document
---

Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(survival)
library(finalfit)
```

Data Creation
```{r message=FALSE, warning=FALSE}
data <- read_csv("../data/data.csv") %>% 
    mutate(init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1,
                          as.numeric(init_performance_status) < 90 ~ 0), levels = c(1, 0), labels = c(">=90", "<90")),
    age_cat = factor(age_cat, levels = c(1, 2, 3), labels = c("21-39", "40-59", ">60")),
    hiv_status = factor(hiv_status, levels = c(0, 1), labels = c("HIV-uninfected", "HIV-infected")),
    marital = factor(marital, levels = c(3, 1, 2), labels = c("Single", "Married/partnered", "Divorced/widowed")),
    total_chemo_received_0 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "1" = "1", "1" = "2", "1" = "3", "1" = "4", "1" = "5", "1" = "6", "1" = "7"), labels = c("0", ">0")),
    total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", "1" = "4", "1" = "5", "1" = "6", "1" = "7"), labels = c("<4", ">=4")),
        combined_cancer_stage = factor(combined_cancer_stage, levels = c(0, 1, 2, 3, 4), labels = c("I (IB1*, IB2)", "I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB)", "IV")),
    # combined_cancer_stage = factor(combined_cancer_stage, levels = c(1, 2, 3, 4), labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III (IIIA, IIIB)", "IV")),
    cd4_cat = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                               hiv_status == "HIV-infected" & cd4_final >= 500 ~ 2, 
                               hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 3,
                               hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 4,
                               hiv_status == "HIV-infected" & cd4_final < 200 ~ 5), levels = c(1,2,3,4)),
    time_alive_path = time_alive_path/365
  )

label(data$age_cat) <- "Age"
label(data$hiv_status) <- "HIV Status"
label(data$cr_result) <- "Baseline Cr"
label(data$hb_result) <- "Baseline Hb"
label(data$eqd2) <- "EQD2"
label(data$combined_cancer_stage) <- "Disease stage"
label(data$total_chemo_received_0) <- "No. of chemo cycles received"
label(data$total_chemo_received_4) <- "No. of chemo cycles received"
```

Create Table 2b
```{r}
explanatory <- c("age_cat", "hiv_status", "hb_result")

explanatory2 <- c("init_performance_status", "marital", "alb_result", "distance", "age_cat", "hiv_status", "hb_result")

dependent <- "Surv(time_alive_path, vital_status)"

# Table with chemo cycles (<4 & >=4)
data %>%
  filter(surgery == 1) %>%
  mutate(combined_cancer_stage_exact = factor(case_when(
    combined_cancer_stage_exact == "1.0" ~ 1,
    combined_cancer_stage_exact == "2.0" ~ 1,
    combined_cancer_stage_exact == "3.0" ~ 1,
    combined_cancer_stage_exact == "4.0" ~ 2,
    combined_cancer_stage_exact == "5.0" ~ 2))) %>%
  finalfit(dependent, explanatory) %>%
  knitr::kable()

data %>%
  filter(surgery == 1) %>%
  mutate(combined_cancer_stage_exact = factor(case_when(
    combined_cancer_stage_exact == "1.0" ~ 1,
    combined_cancer_stage_exact == "2.0" ~ 1,
    combined_cancer_stage_exact == "3.0" ~ 1,
    combined_cancer_stage_exact == "4.0" ~ 2,
    combined_cancer_stage_exact == "5.0" ~ 2))) %>%
  finalfit(dependent, explanatory2) %>%
  knitr::kable()

```
