---
title: "Linear Regression"
author: "Jessica George and Shawna Tuli"
date: "4/11/2021"
output: html_document
---

# Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(finalfit)
library(survival)
library(lubridate)

source("../format_data.R")
```

# Data
```{r message=FALSE, warning=FALSE}
data <- read_excel("../../data/time_to_treatment_data.xlsx") %>% 
  format_data(article_number = 3)
```

# Functions
```{r}
overall_univariate_regression <- function(predictor) {
  formula <- as.formula(paste("path_to_treatment_difference", predictor, sep = " ~ "))
  model <- glm(formula, family = "gaussian", data = data)
  return(model)
}
```

# Univariate Results
```{r results="asis"}
uni_predictors <- c("init_performance_status", "age_cat", "hiv_status", "hiv_cd4_cat", "hiv_cd4_cat2", "hb_result", "combined_cancer_stage", "total_chemo_received_4", "eqd2")

for (uni_predictor in uni_predictors) {
  cat("\n## Path to Treatment Time Difference ~ ", uni_predictor, "  \n")
  model <- overall_univariate_regression(uni_predictor)
  cat("```")
  print(summary(model))
  cat("```")
}
```

# Multivariate Regression Models
```{r}
model1 <- glm(path_to_treatment_difference ~ init_performance_status + age_cat + hiv_status + hb_result + combined_cancer_stage + total_chemo_received_4 + eqd2, family = "gaussian", data = data)
summary(model1)

# Excluding performance status
model2 <- glm(path_to_treatment_difference ~ age_cat + hiv_status + hb_result + combined_cancer_stage + total_chemo_received_4 + eqd2, family = "gaussian", data = data)
summary(model2)

# HIV_CD4_cat instead of HIV status
model3 <- glm(path_to_treatment_difference ~ init_performance_status + age_cat + hiv_cd4_cat + hb_result + combined_cancer_stage + total_chemo_received_4 + eqd2, family = "gaussian", data = data)
summary(model3)

# HIV_CD4_cat2 instead of HIV status
model4 <- glm(path_to_treatment_difference ~ init_performance_status + age_cat + hiv_cd4_cat2 + hb_result + combined_cancer_stage + total_chemo_received_4 + eqd2, family = "gaussian", data = data)
summary(model4)

# Excluding performance status, chemo, and eqd2
model5 <- glm(path_to_treatment_difference ~ age_cat + hiv_status + combined_cancer_stage, family = "gaussian", data = data)
summary(model5)

# Excluding performance status and stage
model6 <- glm(path_to_treatment_difference ~ age_cat + hiv_status + total_chemo_received_4 + eqd2, family = "gaussian", data = data)
summary(model6)
```