---
title: "Table 1"
author: "Jessica George and Shawna Tuli"
date: "4/5/2021"
output:
  pdf_document: default
  html_document: default
---

# Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(survival)
library(lubridate)
library(Table1)

source("../format_data.R")
```

# Data
```{r message=FALSE, warning=FALSE}
data <- read_excel("../../data/time_to_treatment_data.xlsx") %>% 
  format_data(article_number = 3)
```


Treatment Delay Summary Stats
--------------------------------

Min = 0 days

Mean = 134 days (Max = 2,512 days!)

Median = 77 days


# Create Table 1
## Using cut-off at 90 days
```{r}
# Skipping HIV+ only variables: cd4_final, hiv_cd4_cat, hiv_cd4_cat2, on_arv, vl_detect... See below for calculations for these variables

make.table(dat = data,
           strat = "path_treatment_90",
           colnames = c("Characteristic", "Delay <90 days", "Delay >=90 days", "Overall", "P"),
           cat.varlist = c("age_cat", "marital", "cancer_screening", "combined_cancer_stage", "vaginal_hemorrhage_symp", "vaginal_discharge_symp", "pelvic_pain_symp", "init_performance_status", "treat_response", "rt", "crt", "treatment", "chemo", "ebrt_40", "brachy_cat", "eqd2_75", "total_chemo_received_4", "treat_response", "total_chemo_received_cat"),
           cat.rmstat = list(c("row"), c("miss")),
           cat.ptype = "chisq",
           cont.varlist = c("enroll_age", "distance", "cr_result", "hb_result", "neut_result", "wbc_result", "alb_result", "total_chemo_received", "eqd2", "treat_duration"),
           cont.ptype = "ttest",
           cont.rmstat = list(c("", "meansd", ""), c("q1q3")),
           caption = "Table 1",
           footer = "IB1 includes patients who have received chemoradiation therapy, excluding those who have received surgery.<br><i>Abbreviations:</i> ANC = absolute neutrophil count; ARV = antiretroviral; KPS = Karofsky performance score; WBC = white blood cells.<br>Values are presented as number (percentage), unless otherwise noted.",
           tspanner     = c("",""),
            n.tspanner   = c(103.5,103.5),
            cgroup       = c("", "Results by Treatment Delay (90 days)", ""),
            n.cgroup     = c(1, 3, 1),
           output = "html")

# cd4_final
# median
sapply(select(filter(data, hiv_status == "HIV-infected" & path_treatment_90 == "<90"), cd4_final), median, na.rm = T)
sapply(select(filter(data, hiv_status == "HIV-uninfected" & path_treatment_90 == ">=90"), cd4_final), median, na.rm = T)
# quantiles
quantile(select(filter(data,  hiv_status == "HIV-infected" & path_treatment_90 == "<90"), cd4_final), probs = c(0.25, 0.75), na.rm = T)
quantile(select(filter(data,  hiv_status == "HIV-uninfected" & path_treatment_90 == ">=90"), cd4_final), probs = c(0.25, 0.75), na.rm = T)

# hiv_cd4_cat
# counts
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == "<90") %>% group_by(hiv_cd4_cat) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == ">=90") %>% group_by(hiv_cd4_cat) %>% summarise(n())

# hiv_cd4_cat2
# counts
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == "<90") %>% group_by(hiv_cd4_cat2) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == ">=90") %>% group_by(hiv_cd4_cat2) %>% summarise(n())

# vl_final
# mean
sapply(select(filter(data, hiv_status == "HIV-infected" & path_treatment_90 == "<90"), vl_final), median, na.rm = T)
# quantiles
quantile(select(filter(data, hiv_status == "HIV-infected" & path_treatment_90 == ">=90"), vl_final), probs = c(0.25, 0.75), na.rm = T)

# on_arv
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == "<90") %>% group_by(on_arv) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == ">=90") %>% group_by(on_arv) %>% summarise(n())

# vl_detect
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == "<90") %>% group_by(vl_detect) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_90 == ">=90") %>% group_by(vl_detect) %>% summarise(n())
```

# Create Table 1
## Using cut-off at 120 days
```{r}
# Skipping HIV+ only variables: cd4_final, hiv_cd4_cat, hiv_cd4_cat2, on_arv, vl_detect... See below for calculations for these variables

make.table(dat = data,
           strat = "path_treatment_120",
           colnames = c("Characteristic", "Delay <120 days", "Delay >=120 days", "Overall", "P"),
           cat.varlist = c("age_cat", "marital", "cancer_screening", "combined_cancer_stage", "vaginal_hemorrhage_symp", "vaginal_discharge_symp", "pelvic_pain_symp", "init_performance_status", "treat_response", "rt", "crt", "treatment", "chemo", "ebrt_40", "brachy_cat", "eqd2_75", "total_chemo_received_4", "treat_response", "total_chemo_received_cat"),
           cat.rmstat = list(c("row"), c("miss")),
           cat.ptype = "chisq",
           cont.varlist = c("enroll_age", "distance", "cr_result", "hb_result", "neut_result", "wbc_result", "alb_result", "total_chemo_received", "eqd2", "treat_duration"),
           cont.ptype = "ttest",
           cont.rmstat = list(c("", "meansd", ""), c("q1q3")),
           caption = "Table 1",
           footer = "IB1 includes patients who have received chemoradiation therapy, excluding those who have received surgery.<br><i>Abbreviations:</i> ANC = absolute neutrophil count; ARV = antiretroviral; KPS = Karofsky performance score; WBC = white blood cells.<br>Values are presented as number (percentage), unless otherwise noted.",
           tspanner     = c("",""),
            n.tspanner   = c(103.5,103.5),
            cgroup       = c("", "Results by Treatment Delay (120 days)", ""),
            n.cgroup     = c(1, 3, 1),
           output = "html")

# cd4_final
# median
sapply(select(filter(data, hiv_status == "HIV-infected" & path_treatment_120 == "<120"), cd4_final), median, na.rm = T)
sapply(select(filter(data, hiv_status == "HIV-uninfected" & path_treatment_120 == ">=120"), cd4_final), median, na.rm = T)
# quantiles
quantile(select(filter(data,  hiv_status == "HIV-infected" & path_treatment_120 == "<120"), cd4_final), probs = c(0.25, 0.75), na.rm = T)
quantile(select(filter(data,  hiv_status == "HIV-uninfected" & path_treatment_120 == ">=120"), cd4_final), probs = c(0.25, 0.75), na.rm = T)

# hiv_cd4_cat
# counts
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == "<120") %>% group_by(hiv_cd4_cat) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == ">=120") %>% group_by(hiv_cd4_cat) %>% summarise(n())

# hiv_cd4_cat2
# counts
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == "<120") %>% group_by(hiv_cd4_cat2) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == ">=120") %>% group_by(hiv_cd4_cat2) %>% summarise(n())

# vl_final
# mean
sapply(select(filter(data, hiv_status == "HIV-infected" & path_treatment_120 == "<120"), vl_final), median, na.rm = T)
# quantiles
quantile(select(filter(data, hiv_status == "HIV-infected" & path_treatment_120 == ">=120"), vl_final), probs = c(0.25, 0.75), na.rm = T)

# on_arv
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == "<120") %>% group_by(on_arv) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == ">=120") %>% group_by(on_arv) %>% summarise(n())

# vl_detect
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == "<120") %>% group_by(vl_detect) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_120 == ">=120") %>% group_by(vl_detect) %>% summarise(n())
```

# Create Table 1
## Using cut-off at 150 days
```{r}
# Skipping HIV+ only variables: cd4_final, hiv_cd4_cat, hiv_cd4_cat2, on_arv, vl_detect... See below for calculations for these variables

make.table(dat = data,
           strat = "path_treatment_150",
           colnames = c("Characteristic", "Delay <150 days", "Delay >=150 days", "Overall", "P"),
           cat.varlist = c("age_cat", "marital", "cancer_screening", "combined_cancer_stage", "vaginal_hemorrhage_symp", "vaginal_discharge_symp", "pelvic_pain_symp", "init_performance_status", "treat_response", "rt", "crt", "treatment", "chemo", "ebrt_40", "brachy_cat", "eqd2_75", "total_chemo_received_4", "treat_response", "total_chemo_received_cat"),
           cat.rmstat = list(c("row"), c("miss")),
           cat.ptype = "chisq",
           cont.varlist = c("enroll_age", "distance", "cr_result", "hb_result", "neut_result", "wbc_result", "alb_result", "total_chemo_received", "eqd2", "treat_duration"),
           cont.ptype = "ttest",
           cont.rmstat = list(c("", "meansd", ""), c("q1q3")),
           caption = "Table 1",
           footer = "IB1 includes patients who have received chemoradiation therapy, excluding those who have received surgery.<br><i>Abbreviations:</i> ANC = absolute neutrophil count; ARV = antiretroviral; KPS = Karofsky performance score; WBC = white blood cells.<br>Values are presented as number (percentage), unless otherwise noted.",
           tspanner     = c("",""),
            n.tspanner   = c(103.5,103.5),
            cgroup       = c("", "Results by Treatment Delay (150 days)", ""),
            n.cgroup     = c(1, 3, 1),
           output = "html")

# cd4_final
# median
sapply(select(filter(data, hiv_status == "HIV-infected" & path_treatment_150 == "<150"), cd4_final), median, na.rm = T)
sapply(select(filter(data, hiv_status == "HIV-uninfected" & path_treatment_150 == ">=150"), cd4_final), median, na.rm = T)
# quantiles
quantile(select(filter(data,  hiv_status == "HIV-infected" & path_treatment_150 == "<150"), cd4_final), probs = c(0.25, 0.75), na.rm = T)
quantile(select(filter(data,  hiv_status == "HIV-uninfected" & path_treatment_150 == ">=150"), cd4_final), probs = c(0.25, 0.75), na.rm = T)

# hiv_cd4_cat
# counts
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == "<150") %>% group_by(hiv_cd4_cat) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == ">=150") %>% group_by(hiv_cd4_cat) %>% summarise(n())

# hiv_cd4_cat2
# counts
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == "<150") %>% group_by(hiv_cd4_cat2) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == ">=150") %>% group_by(hiv_cd4_cat2) %>% summarise(n())

# vl_final
# mean
sapply(select(filter(data, hiv_status == "HIV-infected" & path_treatment_150 == "<150"), vl_final), median, na.rm = T)
# quantiles
quantile(select(filter(data, hiv_status == "HIV-infected" & path_treatment_150 == ">=150"), vl_final), probs = c(0.25, 0.75), na.rm = T)

# on_arv
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == "<150") %>% group_by(on_arv) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == ">=150") %>% group_by(on_arv) %>% summarise(n())

# vl_detect
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == "<150") %>% group_by(vl_detect) %>% summarise(n())
data %>% filter(hiv_status == "HIV-infected" & path_treatment_150 == ">=150") %>% group_by(vl_detect) %>% summarise(n())
```