---
title: "Table 1"
author: "Shawna Tuli and Jessica George"
date: "3/15/2021"
output: html_document
---

# Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(Table1)

source("../format_data.R")
```

# Data
```{r message=FALSE, warning=FALSE}
treatment_patients <- read_csv("../../data/data.csv") %>% 
  format_data(article_number = 2)
```

# Create Table 1
```{r}
# Skipping HIV+ only variables: cd4_final, cd4_pos_cat, cd4_pos_cat2, on_arv, vl_detect... See below for calculations for these variables

make.table(dat = treatment_patients,
           strat = "hiv_status",
           colnames = c("Characteristic", "HIV-infected", "HIV-uninfected", "Overall", "P"),
           cat.varlist = c("age_cat", "marital", "cancer_screening", "combined_cancer_stage", "vaginal_hemorrhage_symp", "vaginal_discharge_symp", "pelvic_pain_symp", "init_performance_status", "chemo", "ebrt_40", "brachy_20", "eqd2_75", "treat_response"),
           cat.rmstat = list(c("row"), c("miss")),
           cat.ptype = "chisq",
           cont.varlist = c("enroll_age", "distance", "cr_result", "hb_result", "neut_result", "wbc_result", "alb_result", "total_chemo_received", "eqd2", "treat_duration"),
           cont.ptype = "ttest",
           cont.rmstat = list(c("", "meansd", ""), c("q1q3")),
           caption = "Table 1a",
           footer = "IB1 includes patients who have received chemoradiation therapy, excluding those who have received surgery.<br><i>Abbreviations:</i> ANC = absolute neutrophil count; ARV = antiretroviral; EBRT = external beam radiation therapy; EQD2 = radiobiological equivalent dose; KPS = Karofsky performance score; WBC = white blood cells.<br>Values are presented as number (percentage), unless otherwise noted.",
           tspanner     = c("",""),
            n.tspanner   = c(79.5, 79.5),
            cgroup       = c("", "Results by HIV Status", ""),
            n.cgroup     = c(1, 3, 1),
            
           output = "html")
# cd4_final
# median
sapply(select(filter(treatment_patients, hiv_status == "HIV-infected"), cd4_final), median, na.rm = T)
# quantiles
quantile(select(filter(treatment_patients, hiv_status == "HIV-infected"), cd4_final), probs = c(0.25, 0.75), na.rm = T)

# cd4_pos_cat
# counts
treatment_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(cd4_pos_cat) %>% summarise(n())

# cd4_pos_cat2
# counts
treatment_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(cd4_pos_cat2) %>% summarise(n())

# vl_final
# mean
sapply(select(filter(treatment_patients, hiv_status == "HIV-infected"), vl_final), median, na.rm = T)
# quantiles
quantile(select(filter(treatment_patients, hiv_status == "HIV-infected"), vl_final), probs = c(0.25, 0.75), na.rm = T)

# on_arv
treatment_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(on_arv) %>% summarise(n())

# vl_detect
treatment_patients %>% filter(hiv_status == "HIV-infected") %>% group_by(vl_detect) %>% summarise(n())
```