---
title: "Table 3"
author: "Shawna Tuli and Jessica George"
date: "3/15/2021"
output: html_document
---

# Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(survival)
library(Table1)

source("../format_data.R")
```

# Data Creation
```{r message=FALSE, warning=FALSE}
data <- read_csv("../../data/data.csv") %>% 
  format_data(article_number = 2)
```

# Create response variables
```{r}
data <- data %>%
  mutate(
    hb_response = factor(case_when(
      hb_tox_grade <= 1 ~ 0,
      hb_tox_grade > 1 ~ 1
    )),
    cr_response = factor(case_when(
      cr_tox_grade <= 1 ~ 0,
      cr_tox_grade > 1 ~ 1
    )),
    neut_response = factor(case_when(
      neut_tox_grade <= 1 ~ 0,
      neut_tox_grade > 1 ~ 1
    )),
    wbc_response = factor(case_when(
      wbc_tox_grade <= 1 ~ 0,
      wbc_tox_grade > 1 ~ 1
    )),
    alb_response = factor(case_when(
      alb_tox_grade <= 1 ~ 0,
      alb_tox_grade > 1 ~ 1
    )),
    GI_response = factor(case_when(
      nausea_tox <= 1 | vomiting_tox <= 1 | diarrhea_tox <= 1 ~ 0,
      nausea_tox > 1 | vomiting_tox > 1 | diarrhea_tox > 1 ~ 1
    )),
    GU_response = factor(case_when(
      urine_freq_tox <= 1 | urine_incontinence_tox <= 1 | urine_urge_tox <= 1 ~ 0,
      urine_freq_tox > 1 | urine_incontinence_tox > 1 | urine_urge_tox > 1 ~ 1
    )),
    vaginal_response = factor(case_when(
      vaginal_hemorrhage_tox <= 1 | vaginal_discharge_tox <= 1 | pelvic_pain_tox <= 1 ~ 0,
      vaginal_hemorrhage_tox > 1 | vaginal_discharge_tox > 1 | pelvic_pain_tox > 1 ~ 1
    )),
    fatigue_response = factor(case_when(
      fatigue_tox <= 1 ~ 0,
      fatigue_tox > 1 ~ 1
    )),
    dermatitis_response = factor(case_when(
      dermatitis_tox <= 1 ~ 0,
      dermatitis_tox > 1 ~ 1
    ))
  )
```

# Find how many patients have value for each toxicity (high or low grades)
```{r}
data %>% 
  filter((cr_response == 0 | cr_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((hb_response == 0 | hb_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((neut_response == 0 | neut_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((wbc_response == 0 | wbc_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((alb_response == 0 | alb_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((GI_response == 0 | GI_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((GU_response == 0 | GU_response == 1) & crt == 1) %>%
  summarise(n())

data %>% 
  filter((vaginal_response == 0 | vaginal_response == 1) & crt == 1) %>% 
  summarise(n())

data %>% 
  filter((dermatitis_response == 0 | dermatitis_response == 1) & crt == 1) %>% 
  summarise(n())
```

# Find how many patients have value for each toxicity (high grades only) by HIV status
```{r}
data %>% 
  filter(hb_response == 1 & crt == 1) %>% group_by(hiv_status) %>% 
  summarise(n()/222)

data %>% 
  filter(neut_response == 1 & crt == 1) %>% group_by(hiv_status) %>% 
  summarise(n()/145)

data %>% 
  filter(wbc_response == 1 & crt == 1) %>% 
  group_by(hiv_status) %>% 
  summarise(n()/294)
```

# Find how many patients have value for each toxicity (high grades only) by treatment type (CRT or RT alone)
```{r}
data %>% 
  filter(cr_response == 1) %>% 
  group_by(crt) %>% 
  summarise(n()/52)

data %>% 
  filter(hb_response == 1) %>% 
  group_by(crt) %>% 
  summarise(n()/222)

data %>% 
  filter(neut_response == 1) %>% 
  group_by(crt) %>% 
  summarise(n()/145)

data %>% 
  filter(wbc_response == 1) %>% 
  group_by(crt) %>% 
  summarise(n()/294)

data %>% 
  filter(alb_response == 1) %>% 
  group_by(crt) %>% 
  summarise(n()/87)
```

# Create Table 3
```{r}
make.table(dat = data,
           strat = "crt",
           colnames = c("Characteristic", "RT", "CRT", "Overall", "P"),
           cat.varlist = c("hb_response", "cr_response", "neut_response", "wbc_response", "alb_response", "GI_response", "GU_response", "vaginal_response", "fatigue_response", "dermatitis_response"),
           cat.rmstat = list(c("row"), c("miss")),
           cat.ptype = "chisq",
           caption = "Table 3",
           footer = "IB1 includes patients who have received chemoradiation therapy, excluding those who have received surgery.<br><i>Abbreviations:</i> ANC = absolute neutrophil count; ARV = antiretroviral; EBRT = external beam radiation therapy; EQD2 = radiobiological equivalent dose; KPS = Karofsky performance score; WBC = white blood cells.<br>Values are presented as number (percentage), unless otherwise noted.",
           tspanner     = c("",""),
            n.tspanner   = c(32.5, 32.5),
            cgroup       = c("", "Results by CRT/RT", ""),
            n.cgroup     = c(1, 3, 1),
            
           output = "html")
```