format_data <- function(clean_data, article_number) {
  #'Function formats the data for a given article
  #'Current articles: 1, 2, 3, or 4
  #'Input: data (dataframe), article_number(int)
  #'Output: Returns formatted data
  if (article_number == 1) {
    formatted_data <- clean_data %>% 
      mutate(
        hiv_status = relevel(factor(hiv_status, 
                            levels = c(1, 0), 
                            labels = c("HIV-infected", "HIV-uninfected")), ref="HIV-uninfected"),
        hiv_cd4_cat = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 500 ~ 4,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 3,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 2),
                             levels = c(1, 2, 3, 4), 
                             labels = c("HIV-", "<350", ">=350-<500", ">=500")),
        hiv_cd4_cat2 = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 500 ~ 5, 
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 4,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 2), 
                              levels = c(1, 2, 3, 4, 5), 
                              labels = c("HIV-","<200", ">=200-<350", ">=350-<500", ">=500")),
        age_cat = factor(age_cat, 
                         levels = c(1, 2, 3), 
                         labels = c("21-39", "40-59", ">60")),
        marital = factor(marital, 
                         levels = c(3, 1, 2), 
                         labels = c("Single", "Married/partnered", "Divorced/widowed")),
        cancer_screening = factor(cancer_screening, 
                                  levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        distance_factored = factor(case_when(distance == 0 ~ 0,
                                             distance == 59.2 ~ 1,
                                             distance == 94.6 ~ 2,
                                             distance == 310 ~ 3,
                                             distance == 410 ~ 4,
                                             distance == 433 ~ 5,
                                             distance == 517 ~ 6,
                                             distance == 668 ~ 7,
                                             distance == 849 ~ 8,
                                             distance == 1074 ~ 9),
                                   levels = c(0,1,2,3,4,5,6,7,8,9),
                                   labels = c("0 km (South-east)", "59.2 km (Kweneng)", "94.6 km (Southern)",
                                              "310 km (Central or Boteti)", "410 km (Kgatleng)", "433 km (North-east)",
                                              "517 km (Kgalagadi)", "668 km (Ghanzi)", "849 km (Ngamiland)", "1074 km (None above)")),
        distance_factored2 = factor(case_when(distance == 0 ~ 0,
                                             distance == 59.2 ~ 0,
                                             distance == 94.6 ~ 0,
                                             distance == 310 ~ 1,
                                             distance == 410 ~ 1,
                                             distance == 433 ~ 1,
                                             distance == 517 ~ 2,
                                             distance == 668 ~ 2,
                                             distance == 849 ~ 2,
                                             distance == 1074 ~ 2),
                                   levels = c(0,1,2),
                                   labels = c("<100 km (South-east, Kweneng, Southern)",
                                              "100-500 km (Central or Boteti, Kgatleng, North-east)",
                                              "500+ km (Kgalagadi, Ghanzi, Ngamiland, None above)")),
        combined_cancer_stage_exact_factored = factor(combined_cancer_stage_exact, 
                                                      levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15), 
                                                      labels = c("I (IA, IA1, IA2, IB1*, IB2, IB3)", "I (IA, IA1, IA2, IB1*, IB2, IB3)", "I (IA, IA1, IA2, IB1*, IB2, IB3)", "I (IA, IA1, IA2, IB1*, IB2, IB3)", "I (IA, IA1, IA2, IB1*, IB2, IB3)", "I (IA, IA1, IA2, IB1*, IB2, IB3)", 
                                                                 "II (IIA / IIB)", "II (IIA / IIB)", "III (IIIA / IIIB / IIIC)", 
                                                                 "III (IIIA / IIIB / IIIC)", "IV (IVA / IVB)", "IV (IVA / IVB)", 
                                                                 "I (IA, IA1, IA2, IB1*, IB2, IB3)", "III (IIIA / IIIB / IIIC)")),
        combined_cancer_stage_exact_factored2 = factor(combined_cancer_stage_exact, 
                                                      levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15), 
                                                      labels = c("I (A)", "I (A)", "I (A)", "I (B)", "I (B)", "I (B)", 
                                                                 "II (IIA / IIB)", "II (IIA / IIB)", "III (IIIA / IIIB / IIIC)", 
                                                                 "III (IIIA / IIIB / IIIC)", "IV (IVA / IVB)", "IV (IVA / IVB)", 
                                                                 "I (B)", "III (IIIA / IIIB / IIIC)")),
        combined_cancer_stage_exact_factored3 = factor(combined_cancer_stage_exact, 
                                                       levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15), 
                                                       labels = c("I", "I", "I", "I", "I", "I", 
                                                                  "II (IIA / IIB)", "II (IIA / IIB)", "III (IIIA / IIIB / IIIC)", 
                                                                  "III (IIIA / IIIB / IIIC)", "IV (IVA / IVB)", "IV (IVA / IVB)", 
                                                                  "I", "III (IIIA / IIIB / IIIC)")),
        combined_cancer_stage_nonnumerical = factor(combined_cancer_stage_exact,
                                                    levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15),
                                                    labels = c("IA", "IA1", "IA2", "IB", "IB1", "IB2", "IIA",
                                                               "IIB", "IIIA", "IIIB", "IVA", "IVB", "IB3", "IIIC")),
        hb_opt = factor(ifelse(hb_result > 10, 1, 0), levels = c(0,1), labels = c("<=10", ">10")),
        cr_result_s100 = cr_result/100,
        cr_opt = factor(ifelse(cr_result >= 86, 1, 0), levels = c(0,1), labels = c("<86", ">=86")),
        cr_med = factor(ifelse(cr_result >= 60, 1, 0), levels = c(0,1), labels = c("<60", ">=60")),
        neut_opt = factor(ifelse(neut_result >= 3.6, 1, 0), levels = c(0,1), labels = c("<3.6", ">=3.6")),
        neut_med = factor(ifelse(neut_result >= 3.9, 1, 0), levels = c(0,1), labels = c("<3.9", ">=3.9")),
        wbc_opt = factor(ifelse(wbc_result >= 8.5, 1, 0), levels = c(0,1), labels = c("<8.5", ">=8.5")),
        wbc_med = factor(ifelse(wbc_result >= 6.4, 1, 0), levels = c(0,1), labels = c("<6.4", ">=6.4")),
        alb_opt = factor(ifelse(alb_result >= 36.7, 1, 0), levels = c(0,1), labels = c("<36.7", ">=36.7")),
        alb_med = factor(ifelse(alb_result >= 39, 1, 0), levels = c(0,1), labels = c("<39", ">=39")),        
        neut_result_s100 = neut_result/100,
        wbc_result_s100 = wbc_result/100,
        alb_result_s100 = alb_result/100,
        vaginal_hemorrhage_symp = factor(vaginal_hemorrhage_symp, 
                                         levels = c(0, 1), 
                                         labels = c("No", "Yes")),
        vaginal_discharge_symp = factor(vaginal_discharge_symp, 
                                        levels = c(0, 1), 
                                        labels = c("No", "Yes")),
        pelvic_pain_symp = factor(pelvic_pain_symp, 
                                  levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1, 
                                                   as.numeric(init_performance_status) < 90 ~ 0), 
                                         levels = c(1, 0), labels = c(">=90", "<90")),
        cd4_pos_cat = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 3), 
                             levels = c(1, 2, 3), labels = c(">=500", ">=350-<500", "<350")),
        cd4_pos_cat2 = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 4), 
                              levels = c(1, 2, 3, 4), 
                              labels = c(">=500", ">=350-<500", ">=200-<350", "<200")),
        on_arv = factor(on_arv, levels = c(0, 1), labels = c("No", "Yes")),
        chemo = factor(chemo, levels = c(0, 1), labels = c("0", ">=1")),
        ebrt_40 = factor(case_when(ebrt_curr_dose >= 40 ~ 1, 
                                   ebrt_curr_dose < 40 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        brachy_cat = factor(case_when(is.na(as.numeric(brachy_curr_dose)) ~ 0, 
                                      as.numeric(brachy_curr_dose) > 0 ~ 1),
                            levels = c(0, 1),
                            labels = c("No", "Yes")),
        eqd2_75 = relevel(factor(case_when(eqd2 >= 75 ~ 1,
                                   eqd2 < 75 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")), ref="Yes"),
        eqd2_79= relevel(factor(case_when(eqd2 >= 79 ~ 1,
                                           eqd2 < 79 ~ 0), 
                                 levels = c(0, 1), labels = c("No", "Yes")), ref="Yes"),
        eqd2_80 = relevel(factor(case_when(eqd2 >= 80 ~ 1,
                                           eqd2 < 80 ~ 0), 
                                 levels = c(0, 1), labels = c("No", "Yes")), ref="Yes"),
        treat_response = factor(as.numeric(treat_response), 
                                levels = c(1, 2, 5), 
                                labels = c("Complete", "Partial", "Not available")),
        vl_detect = factor(case_when(vl_final < 400 ~ 0,
                                     vl_final >= 400 ~ 1), 
                           levels = c(0, 1), labels = c("Undetectable", "Detectable")),
        vl_detect2 = relevel(factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                              hiv_status == "HIV-infected" & vl_final < 400 ~ 2,
                                              hiv_status == "HIV-infected" & vl_final >= 400 ~ 3,
                                              hiv_status == "HIV-infected" & is.na(vl_final) ~ 4), levels = c(1,2,3,4), labels = c("HIV-", "Undetectable", "Detectable", "Unknown")), ref = "HIV-"),
        vl_detect_cat = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                         hiv_status == "HIV-infected" & vl_final < 400 ~ 2,
                                         hiv_status == "HIV-infected" & vl_final >= 400 ~ 3), 
                               levels = c(1,2,3), labels = c("HIV-", "Undetectable", "Detectable")),
        surgery = factor(surgery, levels = c(0, 1), labels = c("No", "Yes")),
        total_chemo_received_cat = factor(case_when(total_chemo_received == 0 ~ 0,
                                                    total_chemo_received == 1 ~ 1,
                                                    total_chemo_received == 2 ~ 2,
                                                    total_chemo_received == 3 ~ 3,
                                                    total_chemo_received >= 4 ~ 4),
                                          levels = c(0,1,2,3,4), 
                                          labels = c("0", "1", "2", "3", ">=4")),
        total_chemo_received_4 = relevel(factor(case_when(as.numeric(total_chemo_received) < 4 ~ 0, 
                                                         as.numeric(total_chemo_received) >= 4 ~ 1),
                                        levels = c(0, 1),
                                        labels = c("<4", ">=4")), ref=">=4"),
        pathology_year = year(ymd(pathology_date)),
        treatment = factor(treatment, levels = c(0,1), labels = c("No", "Yes")),
        surgery_only = factor(surgery_only, level = c(0,1), labels = c("No", "Yes")),
        rt = factor(rt, level = c(0,1), labels = c("No", "Yes")),
        rt_received = factor(ifelse(rt == "Yes" | crt == "Yes" | primary_surgery_rt == "Yes" | primary_surgery_crt == "Yes", 1, 0), levels = c(0,1), labels = c("No", "Yes")),
        chemo_only = factor(chemo_only, level = c(0,1), labels = c("No", "Yes")),
        crt = factor(crt, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_chemo = factor(primary_surgery_chemo, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_rt = factor(primary_surgery_rt, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_crt = factor(primary_surgery_crt, level = c(0,1), labels = c("No", "Yes")),
        time_alive_path = time_alive_path/365)
  }
  
  else if (article_number == 2) {
    formatted_data <- clean_data %>% 
      filter(primary_surgery_chemo == 0 & primary_surgery_crt == 0 & primary_surgery_rt == 0 & chemo_only == 0 & combined_cancer_stage_exact >= 5) %>% 
      mutate(
        hiv_status = relevel(factor(hiv_status, 
                            levels = c(1, 0), 
                            labels = c("HIV-infected", "HIV-uninfected")), ref = "HIV-uninfected"),
        cd4_pos_cat = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 3), 
                             levels = c(1, 2, 3), 
                             labels = c(">=500", ">=350-<500", "<350")),
        cd4_pos_cat2 = factor(case_when(hiv_status == "HIV-infected" & cd4_final >= 500 ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 2,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 4), levels = c(1, 2, 3, 4), 
                              labels = c(">=500", ">=350-<500", ">=200-<350", "<200")),
        age_cat = factor(age_cat, levels = c(1, 2, 3), 
                         labels = c("21-39", "40-59", ">60")),
        marital = factor(marital, levels = c(3, 1, 2), 
                         labels = c("Single", "Married/partnered", "Divorced/widowed")),
        distance_factored = factor(case_when(distance == 0 ~ 0,
                                             distance == 59.2 ~ 1,
                                             distance == 94.6 ~ 2,
                                             distance == 310 ~ 3,
                                             distance == 410 ~ 4,
                                             distance == 433 ~ 5,
                                             distance == 517 ~ 6,
                                             distance == 668 ~ 7,
                                             distance == 849 ~ 8,
                                             distance == 1074 ~ 9),
                                   levels = c(0,1,2,3,4,5,6,7,8,9),
                                   labels = c("0 km (South-east)", "59.2 km (Kweneng)", "94.6 km (Southern)",
                                              "310 km (Central or Boteti)", "410 km (Kgatleng)", "433 km (North-east)",
                                              "517 km (Kgalagadi)", "668 km (Ghanzi)", "849 km (Ngamiland)", "1074 km (None above)")),
        distance_factored2 = factor(case_when(distance == 0 ~ 0,
                                              distance == 59.2 ~ 0,
                                              distance == 94.6 ~ 0,
                                              distance == 310 ~ 1,
                                              distance == 410 ~ 1,
                                              distance == 433 ~ 1,
                                              distance == 517 ~ 2,
                                              distance == 668 ~ 2,
                                              distance == 849 ~ 2,
                                              distance == 1074 ~ 2),
                                    levels = c(0,1,2),
                                    labels = c("<100 km (South-east, Kweneng, Southern)",
                                               "100-500 km (Central or Boteti, Kgatleng, North-east)",
                                               "500+ km (Kgalagadi, Ghanzi, Ngamiland, None above)")),
        cancer_screening = factor(cancer_screening, levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        combined_cancer_stage = factor(combined_cancer_stage, levels = c(1, 2, 3, 4),
                                       labels = c("I (IB1*, IB2)", "II (IIA, IIB)", "III-IV (IIIA, IIIB, IV)", "III-IV (IIIA, IIIB, IV)")),
        combined_cancer_stage_exact_factored2 = factor(combined_cancer_stage_exact, 
                                                       levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15), 
                                                       labels = c("I (A)", "I (A)", "I (A)", "I (B)", "I (B)", "I (B)", 
                                                                  "II (IIA / IIB)", "II (IIA / IIB)", "III (IIIA / IIIB / IIIC)", 
                                                                  "III (IIIA / IIIB / IIIC)", "IV (IVA / IVB)", "IV (IVA / IVB)", 
                                                                  "I (B)", "III (IIIA / IIIB / IIIC)")),
        vaginal_hemorrhage_symp = factor(vaginal_hemorrhage_symp, levels = c(0, 1),
                                         labels = c("No", "Yes")),
        vaginal_discharge_symp = factor(vaginal_discharge_symp, levels = c(0, 1), 
                                        labels = c("No", "Yes")),
        pelvic_pain_symp = factor(pelvic_pain_symp, levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1,
                                                   as.numeric(init_performance_status) < 90 ~ 0), levels = c(1, 0), labels = c(">=90", "<90")),
        on_arv = factor(on_arv, levels = c(0, 1), labels = c("No", "Yes")),
        chemo = factor(chemo, levels = c(0, 1), labels = c("0", ">=1")),
        ebrt_40 = factor(case_when(ebrt_curr_dose >= 40 ~ 1, 
                                   ebrt_curr_dose < 40 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        brachy_20 = factor(case_when(brachy_curr_dose >= 20 ~ 1, 
                                     brachy_curr_dose < 20 ~ 0), 
                           levels = c(0, 1), labels = c("No", "Yes")),
        eqd2_75 = factor(case_when(eqd2 >= 75 ~ 1,
                                   eqd2 < 75 ~ 0), 
                         levels = c(0, 1), labels = c("No", "Yes")),
        treat_response = factor(as.numeric(treat_response), 
                                levels = c(1, 2, 5), 
                                labels = c("Complete", "Partial", "Not available")),
        vl_detect = factor(case_when(vl_final < 400 ~ 0,
                                     vl_final >= 400 ~ 1), 
                           levels = c(0, 1), labels = c("Undetectable", "Detectable")),
        total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", 
                                                            "1" = "4", "1" = "5", "1" = "6", "1" = "7"), labels = c("<4", ">=4")),
        treatment = factor(treatment, levels = c(0,1), labels = c("No", "Yes")),
        surgery_only = factor(surgery_only, level = c(0,1), labels = c("No", "Yes")),
        rt = factor(rt, level = c(0,1), labels = c("No", "Yes")),
        rt_received = factor(ifelse(rt == "Yes" | crt == "Yes" | primary_surgery_rt == "Yes" | primary_surgery_crt == "Yes", 1, 0), levels = c(0,1), labels = c("No", "Yes")),
        chemo_only = factor(chemo_only, level = c(0,1), labels = c("No", "Yes")),
        crt = factor(crt, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_chemo = factor(primary_surgery_chemo, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_rt = factor(primary_surgery_rt, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_crt = factor(primary_surgery_crt, level = c(0,1), labels = c("No", "Yes")),
        time_alive_path = time_alive_path/365)
  }
  
  else if (article_number == 3) {
    formatted_data <- clean_data %>% 
      # Filter out patients without treatment start date (87) and patients who have negative time to treatment
      # filter(!is.na(actual_treat_start_date) & path_to_treatment_difference >= 0) %>% 
      mutate(   
        age_cat = factor(age_cat, levels = c(1, 2, 3), labels = c("21-39", "40-59", ">60")),
        hiv_status = relevel(factor(hiv_status, 
                                    levels = c(1, 0), 
                                    labels = c("HIV-infected", "HIV-uninfected")), ref="HIV-uninfected"),
        hiv_cd4_cat = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                       hiv_status == "HIV-infected" & cd4_final >= 500 ~ 4,
                                       hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 3,
                                       hiv_status == "HIV-infected" & cd4_final < 350 ~ 2),
                             levels = c(1, 2, 3, 4), 
                             labels = c("HIV-", "<350", ">=350-<500", ">=500")),
        hiv_cd4_cat2 = factor(case_when(hiv_status == "HIV-uninfected" ~ 1,
                                        hiv_status == "HIV-infected" & cd4_final >= 500 ~ 5, 
                                        hiv_status == "HIV-infected" & cd4_final >= 350 & cd4_final < 500 ~ 4,
                                        hiv_status == "HIV-infected" & cd4_final >= 200 & cd4_final < 350 ~ 3,
                                        hiv_status == "HIV-infected" & cd4_final < 200 ~ 2), 
                              levels = c(1, 2, 3, 4, 5), 
                              labels = c("HIV-","<200", ">=200-<350", ">=350-<500", ">=500")),
        marital = factor(marital, levels = c(3, 1, 2), labels = c("Single", "Married/partnered", "Divorced/widowed")),
        distance_factored = factor(case_when(distance == 0 ~ 0,
                                             distance == 59.2 ~ 1,
                                             distance == 94.6 ~ 2,
                                             distance == 310 ~ 3,
                                             distance == 410 ~ 4,
                                             distance == 433 ~ 5,
                                             distance == 517 ~ 6,
                                             distance == 668 ~ 7,
                                             distance == 849 ~ 8,
                                             distance == 1074 ~ 9),
                                   levels = c(0,1,2,3,4,5,6,7,8,9),
                                   labels = c("0 km (South-east)", "59.2 km (Kweneng)", "94.6 km (Southern)",
                                              "310 km (Central or Boteti)", "410 km (Kgatleng)", "433 km (North-east)",
                                              "517 km (Kgalagadi)", "668 km (Ghanzi)", "849 km (Ngamiland)", "1074 km (None above)")),
        distance_factored2 = factor(case_when(distance == 0 ~ 0,
                                              distance == 59.2 ~ 0,
                                              distance == 94.6 ~ 0,
                                              distance == 310 ~ 1,
                                              distance == 410 ~ 1,
                                              distance == 433 ~ 1,
                                              distance == 517 ~ 2,
                                              distance == 668 ~ 2,
                                              distance == 849 ~ 2,
                                              distance == 1074 ~ 2),
                                    levels = c(0,1,2),
                                    labels = c("<100 km (South-east, Kweneng, Southern)",
                                               "100-500 km (Central or Boteti, Kgatleng, North-east)",
                                               "500+ km (Kgalagadi, Ghanzi, Ngamiland, None above)")),
        cancer_screening = factor(cancer_screening, 
                                  levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        vaginal_hemorrhage_symp = factor(vaginal_hemorrhage_symp, 
                                         levels = c(0, 1), 
                                         labels = c("No", "Yes")),
        vaginal_discharge_symp = factor(vaginal_discharge_symp, 
                                        levels = c(0, 1), 
                                        labels = c("No", "Yes")),
        pelvic_pain_symp = factor(pelvic_pain_symp, 
                                  levels = c(0, 1), 
                                  labels = c("No", "Yes")),
        cr_result_s100 = cr_result/100,
        neut_result_s100 = neut_result/100,
        wbc_result_s100 = wbc_result/100,
        alb_result_s100 = alb_result/100,
        treat_response = factor(as.numeric(treat_response), 
                                levels = c(1, 2, 5), 
                                labels = c("Complete", "Partial", "Not available")),
        init_performance_status = factor(case_when(as.numeric(init_performance_status) >= 90 ~ 1, 
                                                   as.numeric(init_performance_status) < 90 ~ 0), levels = c(1, 0), labels = c(">=90", "<90")),
        init_combined_cancer_stage = factor(init_combined_cancer_stage, levels = c(1, 2, 3, 4), labels = c("I (IB1*, IB2, IB3)", "II (IIA, IIB)", "III (IIIA, IIIB, IIIC)", "IV (IVA, IVB)")),
        init_combined_cancer_stage2 = factor(init_combined_cancer_stage, levels = c("I (IB1*, IB2, IB3)", "II (IIA, IIB)", "III (IIIA, IIIB, IIC)", "IV (IVA, IVB)"), labels = c("I-II", "I-II", "III-IV", "III-IV")),
        init_combined_cancer_stage3 = factor(init_combined_cancer_stage, levels = c("I (IB1*, IB2, IB3)", "II (IIA, IIB)", "III (IIIA, IIIB, IIC)", "IV (IVA, IVB)"), labels = c("I", "II-IV", "II-IV", "II-IV")),
        final_combined_cancer_stage = factor(final_combined_cancer_stage, levels = c(1, 2, 3, 4), labels = c("I (IB1*, IB2, IB3)", "II (IIA, IIB)", "III (IIIA, IIIB, IIIC)", "IV (IVA, IVB)")),
        final_combined_cancer_stage2 = factor(final_combined_cancer_stage, levels = c("I (IB1*, IB2, IB3)", "II (IIA, IIB)", "III (IIIA, IIIB, IIC)", "IV (IVA, IVB)"), labels = c("I-II", "I-II", "III-IV", "III-IV")),
        final_combined_cancer_stage3 = factor(final_combined_cancer_stage, levels = c("I (IB1*, IB2, IB3)", "II (IIA, IIB)", "III (IIIA, IIIB, IIC)", "IV (IVA, IVB)"), labels = c("I", "II-IV", "II-IV", "II-IV")),
        total_chemo_received_4 = factor(forcats::fct_recode(factor(total_chemo_received), "0" = "0", "0" = "1", "0" = "2", "0" = "3", "1" = "4", "1" = "5", 
                                                            "1" = "6", "1" = "7"), labels = c("<4", ">=4")),
        total_chemo_received_cat = factor(case_when(total_chemo_received == 0 ~ 0,
                                                    total_chemo_received == 1 ~ 1,
                                                    total_chemo_received == 2 ~ 2,
                                                    total_chemo_received == 3 ~ 3,
                                                    total_chemo_received >= 4 ~ 4), levels = c(0,1,2,3,4), labels = c("0", "1", "2", "3", ">=4")),
        chemo = relevel(factor(chemo, levels = c(0, 1), labels = c("0", ">=1")), ref="0"),
        ebrt_40 = factor(case_when(ebrt_curr_dose >= 40 ~ 1, 
                                   ebrt_curr_dose < 40 ~ 0), levels = c(0, 1), labels = c("No", "Yes")),
        brachy_20 = factor(case_when(brachy_curr_dose >= 20 ~ 1, 
                                     brachy_curr_dose < 20 ~ 0), levels = c(0, 1), labels = c("No", "Yes")),
        brachy_cat = factor(ifelse(brachy_curr_dose > 0, 1, 0), levels = c(0, 1), labels = c("No", "Yes")),
        eqd2_75 = relevel(factor(case_when(eqd2 >= 75 ~ 1,
                                   eqd2 < 75 ~ 0), levels = c(0, 1), labels = c("No", "Yes")), ref="No"),
        eqd2_79 = relevel(factor(case_when(eqd2 >= 79 ~ 1,
                                          eqd2 < 79 ~ 0), 
                                levels = c(0, 1), labels = c("No", "Yes")), ref="No"),
        eqd2_80 = relevel(factor(case_when(eqd2 >= 80 ~ 1,
                                           eqd2 < 80 ~ 0), 
                                 levels = c(0, 1), labels = c("No", "Yes")), ref="No"),
        on_arv = factor(on_arv, levels = c(0, 1), labels = c("No", "Yes")),
        path_treatment_30 = relevel(factor(ifelse(path_to_treatment_difference < 30, 0, 1), 
                                            levels = c(0,1), labels=c("<30", ">=30")),
                                     ref="<30"),
        path_treatment_60 = relevel(factor(ifelse(path_to_treatment_difference < 60, 0, 1), 
                                            levels = c(0,1), labels=c("<60", ">=60")),
                                     ref="<60"),
        path_treatment_84 = relevel(factor(ifelse(path_to_treatment_difference < 84, 0, 1), 
                                           levels = c(0,1), labels=c("<84 days", "≥84 days")),
                                    ref="<84 days"),
        path_treatment_90 = relevel(factor(ifelse(path_to_treatment_difference < 90, 0, 1), 
                                            levels = c(0,1), labels=c("<90 days", "≥90 days")),
                                     ref="<90 days"),
        path_treatment_90_ = factor(ifelse(path_to_treatment_difference < 90, 1, 0)),
        path_treatment_120 = relevel(factor(ifelse(path_to_treatment_difference < 120, 0, 1), 
                                            levels = c(0,1), labels=c("<120", ">=120")),
                                     ref="<120"),
        path_treatment_150 = relevel(factor(ifelse(path_to_treatment_difference < 150, 0, 1), 
                                            levels = c(0,1), labels=c("<150", ">=150")),
                                     ref="<150"),
        path_treatment_180 = relevel(factor(ifelse(path_to_treatment_difference < 180, 0, 1), 
                                            levels = c(0,1), labels=c("<180", ">=180")),
                                     ref="<180"),
        path_treatment_group = factor(case_when(path_to_treatment_difference < 60 ~ 1,
                                                path_to_treatment_difference >= 60 & path_to_treatment_difference < 90 ~ 2,
                                                path_to_treatment_difference >= 90 & path_to_treatment_difference < 120 ~ 3,
                                                path_to_treatment_difference >= 120 ~ 4), levels=c(1,2,3,4), labels=c("<60", "60-<90", "90-<120", ">=120")),
        delay = relevel(factor(case_when(path_to_treatment_difference < 180 ~ 0,
                                         treatment == 0 ~ 1,
                                         path_to_treatment_difference >= 180 ~ 1), levels=c(0,1), labels=c("No Delay", "Delay or Untreated")), ref="No Delay"),
        pathology_year = year(ymd(pathology_date)),
        vl_detect = factor(case_when(vl_final < 400 ~ 0,
                                     vl_final >= 400 ~ 1), levels = c(0, 1), labels = c("Undetectable", "Detectable")),
        pathology_year = year(ymd(pathology_date)),
        pathology_group = factor(case_when(pathology_year < 2016 ~ 2015,
                                           pathology_year == 2016 ~ 2016,
                                           pathology_year == 2017 ~ 2017,
                                           pathology_year == 2018 ~ 2018,
                                           pathology_year == 2019 ~ 2019),
                                 levels=c(2015, 2016, 2017, 2018, 2019), labels=c("<2016", "2016", "2017", "2018", "2019")),
        pathology_group2 = factor(case_when(pathology_year < 2016 ~ 1,
                                            pathology_year == 2016 ~ 2,
                                            pathology_year == 2017 ~ 2,
                                            pathology_year == 2018 ~ 3,
                                            pathology_year == 2019 ~ 3),
                                  levels=c(1,2,3), labels=c("<2016", "2016-2017", "2018-2019")),
        pathology_group3 = factor(case_when(pathology_year < 2016 ~ 1,
                                            pathology_year %in% c(2016, 2017, 2018) ~ 2,
                                            pathology_year >= 2019 ~ 3),
                                  levels=c(1,2,3), labels=c("<2016", "2016-2018", "2019")),
        # 0 if no treatment, 1 if treatment
        treatment = factor(treatment, levels = c(0,1), labels = c("No", "Yes")),
        surgery_only = factor(surgery_only, level = c(0,1), labels = c("No", "Yes")),
        rt = factor(rt, level = c(0,1), labels = c("No", "Yes")),
        rt_received = factor(ifelse(eqd2 > 0, 1, 0), levels = c(0,1), labels = c("No", "Yes")),
        chemo_only = factor(chemo_only, level = c(0,1), labels = c("No", "Yes")),
        crt = factor(crt, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_chemo = factor(primary_surgery_chemo, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_rt = factor(primary_surgery_rt, level = c(0,1), labels = c("No", "Yes")),
        primary_surgery_crt = factor(primary_surgery_crt, level = c(0,1), labels = c("No", "Yes")),
        treatment_type = factor(case_when(rt == "Yes" ~ 0,
                                          crt == "Yes" ~ 1), levels=c(0,1), labels=c("RT", "CRT")),
        time_alive_path_yr = time_alive_path/365,
        time_alive_path_mo = time_alive_path/30.417,
        time_alive_treat_yr = time_alive_treat/365,
        time_alive_treat_mo = time_alive_treat/30.417,
        curative_palliative = relevel(factor(curative_palliative_status), ref="Definitive"),
        vital_status24 = relevel(factor(vital_status24, levels=c(0,1), labels=c("No", "Yes")), ref="No"))
  }

  else {
    print("Function expects data and article number: Returning NULL")
    return(NULL)
  }
  return(formatted_data)
}