---
title: "Survival Curves"
author: "Shawna Tuli and Jessica George"
date: "4/26/2021"
output:
  pdf_document: default
  html_document: default
---

# Libraries
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(survival)
library(survminer)
library(DescTools)
library(patchwork)
```

# Data
```{r message=FALSE, warning=FALSE, include=FALSE}
data <- read_csv("article_4_cleaned_data.csv")
data 
```

# Rename columns
```{r}
data = data %>% rename('HIV' = 'HIV status', 'Vital' = 'Vital status', 'Date' = 'Last Follow up date or date of death of died', 'VL' = 'VL at cancer diagnosis', 'CD4' = 'CD4 at cancer diagnosis', 'Cycles' = 'Cycles of chemo', 'Path' = 'Path response')  
```

# Factor
```{r}
data %>% mutate(hiv_status = factor(HIV), stage = factor(Stage), vl = factor(VL), path = factor(Path)) -> data
data
```

# KMs on All Patients
## 1) Survival status by 1
```{r, fig.width = 8}
stage_survival <- survfit(Surv(date_of_death_and_start_date, Vital) ~ 1, data)

stage_plot <- ggsurvplot(fit = stage_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 5),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates",
  break.time.by = 1,
  palette = c("#333333", "#E69F00", "#009E73"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("All Patients"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
stage_plot$plot <- stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

stage_plot$plot
```
```{r, fig.height = 2, fig.width = 8}
stage_plot$table <- stage_plot$table + theme(plot.title = element_text(hjust = -0.03, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))

stage_plot$table
```

## 2) Cause-specific Survival status (by cancer)
```{r, fig.width = 8}
data <- data %>% filter(`Study ID` != 5397)
data 

stage_survival <- survfit(Surv(date_of_death_and_start_date, Vital) ~ 1, data)

stage_plot <- ggsurvplot(fit = stage_survival,
  data,
  xlab = "Years since pathology report",
  xlim = c(0, 5),
  ylab = "Proportion surviving",
  title = "Kaplan-Meier Survival Estimates for Death by Cancer ",
  break.time.by = 1,
  palette = c("#333333"),
  conf.int = FALSE,
  censor = TRUE,
  legend.title="",
  legend.labs = c("All Patients"),
  risk.table = TRUE,
  risk.table.height = 0.2,
  tables.theme = theme_cleantable())
stage_plot$plot <- stage_plot$plot +
  theme(plot.title = element_text(hjust = 0.4), panel.grid.major.y = element_line(color = "#EAF2F3"), plot.background = element_rect(fill = "#EAF2F3"), axis.title.y = element_text(vjust = 1))

stage_plot$plot
```

```{r, fig.height = 2, fig.width = 8}
stage_plot$table <- stage_plot$table + theme(plot.title = element_text(hjust = -0.03, size = 14), plot.background = element_rect(fill = "#EAF2F3"), panel.background = element_rect(fill = "#EAF2F3"))

stage_plot$table
```

