---
title: "article_4"
author: "Shawna Tuli and Jessica George"
date: "4/19/2021"
output: html_document
---

# Libraries
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(finalfit)
library(lubridate)
library(survival)
```

# Data
```{r message=FALSE, warning=FALSE}
data <- read_csv("article_4_cleaned_data.csv")
data
```

# Rename columns
```{r}
data = data %>% rename('Date' = 'Last Follow up date or date of death of died', 'VL' = 'VL at cancer diagnosis', 'CD4' = 'CD4 at cancer diagnosis', 'Cycles' = 'Cycles of chemo') 
data
```

# Factor
```{r}
data %>% mutate(vital_status = factor("Vital status"), hiv_status = factor("Hiv status"), stage = factor("Stage"), vl = factor("VL")) -> data
```

# To numeric
```{r}
data$Date = as.numeric(data$Date)
data$vital_status = as.numeric(data$vi)
```

# Univariate Results
```{r}
dependent <- "Surv(Date, vital_status)"

values <- c('Age', 'Stage', 'hiv_status', 'Cycles', 'Age', 'CD4') 

for (value in values){
data %>%
  finalfit(dependent, value) %>%
  select("Dependent: Surv(Date, vital_status)", " ", "all", "HR (univariable)") %>% 
  knitr::kable()}
```